#!/usr/bin/env python3
"""Emit a C++ probe that prints sizeof() for every packet struct in the headers.

Phase 0 exits on one condition: the protocol headers compile on Linux and every
struct is the size the shipped binary expects. This generates the program that
answers the second half -- build it, run it, and diff the TSV it prints against
the reference table.

Most structs are declared anonymously as `typedef struct {...} NAME;`, which
puts the name on the closing line, but 140 carry it on the opening line instead
-- either a plain tag or the extended-protocol form `struct FOO : EXTEND_HEADER`.
Both lines are harvested, so 26 structs written `typedef struct FOO_DATA {...}
FOO;` contribute two names for one layout. That is intentional: the code uses
both spellings and both must compile, so the probe sizes both.

Usage:
    python3 tools/gen_struct_probe.py <path-to-SwordOnline/Headers> -o build/struct_probe.cpp
"""
import argparse
import os
import re
import sys

HEADERS = [
    "KProtocolDef.h",
    "KRelayProtocol.h",
    "KProtocol.h",
    "KTongProtocol.h",
    "KGmProtocol.h",
]

# `} PLAYER_SYNC;` and `} tagFOO, *LPFOO;` -- take the first name only.
CLOSE_RE = re.compile(r"^\s*\}\s*([A-Za-z_]\w*)\s*(?:,[^;]*)?;", re.M)
# `struct tagFoo {`, `typedef struct tagFoo {`, and the extended-protocol form
# `struct ASK_ADDFRIEND_CMD : EXTEND_HEADER` -- 91 packets across KProtocol.h and
# KTongProtocol.h derive from a header base, and they are named on the open line
# rather than the close line.
OPEN_RE = re.compile(
    r"^\s*(?:typedef\s+)?struct\s+([A-Za-z_]\w*)\s*(?:\{|:|$)", re.M)

# Names that are unions, enums or forward declarations rather than layouts we
# can size, plus anything the probe cannot instantiate.
SKIP = set()


# `typedef struct FOO_DATA { ... } FOO;` -- one layout under two names. Counted
# so the summary can distinguish names probed from distinct layouts covered.
PAIR_RE = re.compile(
    r"typedef\s+struct\s+([A-Za-z_]\w*)\b[^{;]*\{.*?\}\s*([A-Za-z_]\w*)\s*[,;]",
    re.S)


# Commented-out structs are still structs to a regex. KProtocol.h carries at
# least one (`/*typedef struct {...} DB_PLAYERSELECT_COMMAND;*/`), and probing a
# name that no longer exists fails the build. Strip comments first, replacing
# each with the newlines it spanned so the ^-anchored patterns still see real
# line starts.
COMMENT_RE = re.compile(r"/\*.*?\*/|//[^\n]*", re.S)


def strip_comments(text):
    return COMMENT_RE.sub(lambda m: "\n" * m.group(0).count("\n"), text)


def harvest(header_dir):
    """Return ([(header, struct_name)], alias_count) in declaration order."""
    seen = set()
    out = []
    aliases = 0
    for h in HEADERS:
        path = os.path.join(header_dir, h)
        if not os.path.isfile(path):
            print(f"  ! missing {h}", file=sys.stderr)
            continue
        with open(path, "r", encoding="utf-8", errors="replace") as fh:
            text = strip_comments(fh.read())
        for tag, alias in PAIR_RE.findall(text):
            if tag != alias:
                aliases += 1
        names = CLOSE_RE.findall(text) + OPEN_RE.findall(text)
        for n in names:
            if n in SKIP or n in seen:
                continue
            seen.add(n)
            out.append((h, n))
    return out, aliases


def emit(structs, out_path, header_dir):
    lines = [
        "// GENERATED by tools/gen_struct_probe.py -- do not edit.",
        "//",
        "// Prints one TSV row per packet struct: name, sizeof, source header.",
        "// A row that fails to compile means the header does not build on Linux;",
        "// a size that differs from the reference table means the layout drifted",
        "// and every packet using that struct is now wrong on the wire.",
        "",
        "#include <cstdio>",
        "",
        "#include <windows.h>   // compat/",
        "",
    ]
    for h in HEADERS:
        if os.path.isfile(os.path.join(header_dir, h)):
            lines.append(f'#include "{h}"')
    lines += [
        "",
        "int main(void) {",
        '    std::printf("struct\\tsize\\theader\\n");',
    ]
    for header, name in structs:
        lines.append(
            f'    std::printf("{name}\\t%zu\\t{header}\\n", sizeof({name}));'
        )
    lines += [
        f'    std::fprintf(stderr, "%d structs probed\\n", {len(structs)});',
        "    return 0;",
        "}",
        "",
    ]
    os.makedirs(os.path.dirname(out_path) or ".", exist_ok=True)
    with open(out_path, "w", encoding="utf-8", newline="\n") as fh:
        fh.write("\n".join(lines))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("header_dir", help="path to SwordOnline/Headers")
    ap.add_argument("-o", "--out", default="build/struct_probe.cpp")
    args = ap.parse_args()

    if not os.path.isdir(args.header_dir):
        sys.exit(f"not a directory: {args.header_dir}")

    structs, aliases = harvest(args.header_dir)
    emit(structs, args.out, args.header_dir)

    per_header = {}
    for h, _n in structs:
        per_header[h] = per_header.get(h, 0) + 1
    print(f"wrote {args.out}")
    for h in HEADERS:
        if h in per_header:
            print(f"  {h:22} {per_header[h]:4d} names")
    print(f"  {'TOTAL':22} {len(structs):4d} names")
    print(f"  {'':22} {len(structs) - aliases:4d} distinct layouts "
          f"({aliases} tag/typedef alias pairs)")


if __name__ == "__main__":
    main()
