// GENERATED by tools/gen_protocol.py -- do not edit.
//
// Layouts read out of server1/jx_linux_y's DWARF, not ported from the
// Windows headers, which are wrong for 44% of the structs both trees
// define and missing 236 of the packets this server sends.
//
// 661 types, 2722 fields.
// Sizes and offsets are asserted in src/protocol/jx_layout.cpp.

#ifndef JX_PROTOCOL_H
#define JX_PROTOCOL_H

#include <cstddef>
#include <cstdint>
#include <ctime>

#include <windows.h>   // compat/: BYTE, WORD, DWORD, GUID, ...

#ifndef JX_INT64_DEFINED
#define JX_INT64_DEFINED
typedef int64_t INT64;
#endif

// Every layout below assumes these. On a toolchain where one differs --
// a 64-bit build, or a 32-bit one with _TIME_BITS=64 -- the packets do
// not merely change size, they desynchronise the client. Fail here.
static_assert(sizeof(BYTE) == 1, "BYTE must be 1 byte on the wire");
static_assert(sizeof(CHAR) == 1, "CHAR must be 1 byte on the wire");
static_assert(sizeof(char) == 1, "char must be 1 byte on the wire");
static_assert(sizeof(bool) == 1, "bool must be 1 byte on the wire");
static_assert(sizeof(unsigned char) == 1, "unsigned char must be 1 byte on the wire");
static_assert(sizeof(WORD) == 2, "WORD must be 2 bytes on the wire");
static_assert(sizeof(short int) == 2, "short int must be 2 bytes on the wire");
static_assert(sizeof(short unsigned int) == 2, "short unsigned int must be 2 bytes on the wire");
static_assert(sizeof(DWORD) == 4, "DWORD must be 4 bytes on the wire");
static_assert(sizeof(UINT) == 4, "UINT must be 4 bytes on the wire");
static_assert(sizeof(INT) == 4, "INT must be 4 bytes on the wire");
static_assert(sizeof(BOOL) == 4, "BOOL must be 4 bytes on the wire");
static_assert(sizeof(int) == 4, "int must be 4 bytes on the wire");
static_assert(sizeof(unsigned int) == 4, "unsigned int must be 4 bytes on the wire");
static_assert(sizeof(long unsigned int) == 4, "long unsigned int must be 4 bytes on the wire");
static_assert(sizeof(size_t) == 4, "size_t must be 4 bytes on the wire");
static_assert(sizeof(time_t) == 4, "time_t must be 4 bytes on the wire");
static_assert(sizeof(LPVOID) == 4, "LPVOID must be 4 bytes on the wire");
static_assert(sizeof(INT64) == 8, "INT64 must be 8 bytes on the wire");
static_assert(sizeof(int64_t) == 8, "int64_t must be 8 bytes on the wire");

// ---- enums a packet field refers to ---------------------------------------

enum CurrencyType {
    CURRENCYTYPE_NONE = 0,
    CURRENCYTYPE_MONEY = 1,
    CURRENCYTYPE_FUYUAN = 2,
    CURRENCYTYPE_COIN = 3,
    CURRENCYTYPE_SCORE = 4,
    CURRENCYTYPE_GOLDCOIN = 5,
    CURRENCYTYPE_SLIVER = 6,
    CURRENCYTYPE_TICKET = 7,
    CURRENCYTYPE_YUANBAO = 8,
    CURRENCYTYPE_GOLDCOIN_NEW = 9,
    CURRENCYTYPE_CONTRIBUTION = 10,
    CURRENCYTYPE_HONOUR = 11,
    CURRENCYTYPE_GOLDCOIN_SCORE = 12,
    CURRENCYTYPE_RESPECT = 13,
    CURRENCYTYPE_REFINING = 14,
    CURRENCYTYPE_ENERGY = 15,
    CURRENCYTYPE_ARENA_CREDITS = 16,
    CURRENCYTYPE_END = 17,
};
static_assert(sizeof(CurrencyType) == 4, "CurrencyType");

enum MiniMapObjType {
    MMOT_DEST = 0,
    MMOT_TELLPOS = 1,
    MMOT_HIGHLIGHT = 2,
    MMOT_NUM = 3,
};
static_assert(sizeof(MiniMapObjType) == 4, "MiniMapObjType");

// ---- packets and the types they embed -------------------------------------
//
// pack(1) with padding written out explicitly wherever the binary
// shows a gap, so the layout does not depend on this compiler
// agreeing with the original about alignment.

#pragma pack(push, 1)

struct AUCTION_PROTOCOLHEADER {
    BYTE ProtocolType;
    WORD wProcotolSize;
    BYTE auctionProtocolType;
};

struct CITYWAR_PROTOCOLHEADER {
    BYTE ProtocolType;
    WORD wProcotolSize;
    BYTE CityWarProtocolType;
};

struct CITYWAR_TAXRATES {
    DWORD dwExchangeTax;
    DWORD dwPriceParameter;
};

struct EXTEND_HEADER {
    BYTE ProtocolFamily;
    BYTE ProtocolID;
};

struct FIGHT_PARTNER_SIMPLE_INFO_2_u {
    BYTE m_byInfo[2];
    WORD m_wInfo;
    BYTE _jxpad_0[2];   // trailing padding: this struct is not pack(1) upstream
};

struct FIGHT_PARTNER_SIMPLE_INFO_4_u {
    BYTE m_byInfo[4];
    WORD m_wInfo[2];
    DWORD m_dwInfo;
    BYTE _jxpad_0[4];   // trailing padding: this struct is not pack(1) upstream
};

struct GSTongInfo {
    int nCamp;
    char szTongUnionName[32];
};

struct KACCOUNT_LIMITTIME_INFO {
    DWORD dwLimitTimeFlag;
    DWORD dwLimitTimeOnlineSeconds;
    DWORD dwLimitTimeOfflineSeconds;
};

struct KEMPIRE_DATA {
    char szEmperor[32];
    char szTitle[16];
    char szTong[32];
    BYTE bySex;
    BYTE bySide;
    DWORD dwGoodness;
    DWORD dwBadness;
    DWORD dwBeginTime;
};

struct KILLER_PROTOCOLHEADER {
    BYTE ProtocolType;
    WORD wProcotolSize;
    BYTE killerProtocolType;
};

struct KMagicAttrib {
    int nAttribType;
    int nValue[3];
};

struct KRESIST_ATTR {
    int nCurrentFireResist_Yin;
    int nCurrentColdResist_Yin;
    int nCurrentPoisonResist_Yin;
    int nCurrentLightResist_Yin;
    int nCurrentPhysicsResist_Yin;
    int nCurrentFireResist_Yan;
    int nCurrentColdResist_Yan;
    int nCurrentPoisonResist_Yan;
    int nCurrentLightResist_Yan;
    int nCurrentPhysicsResist_Yan;
    int nCurrentFireResistMax;
    int nCurrentColdResistMax;
    int nCurrentPoisonResistMax;
    int nCurrentLightResistMax;
    int nCurrentPhysicsResistMax;
    int nFireResist;
    int nColdResist;
    int nPoisonResist;
    int nLightResist;
    int nPhysicsResist;
    int nFireResistMax;
    int nColdResistMax;
    int nPoisonResistMax;
    int nLightResistMax;
    int nPhysicsResistMax;
};

struct KRET_APPLYINFO {
    BYTE byLevel;
    BYTE bIsOnline;
    char szName[32];
};

struct KSTAT_DATA_MODIFY {
    int nID;
    int64_t nValue;
};

struct KTongBaseData {
    DWORD dwValue;
    char szTongName[10];
};

struct KTongInfo {
    char szName[32];
    char szMasterName[32];
    DWORD dwMasterID;
    BYTE btSelfCamp;
    INT64 llMoneyFund;
    DWORD dwExpLevel;
    BYTE btUnionLeader;
    BYTE btUnionNum;
    char szUnionName[32];
    WORD nMemberCount;
    WORD nManagerCount;
    WORD nDirectorCount;
    char szMaleTitle[32];
    char szFemaleTitle[32];
};

struct KTongMemberBaseData {
    DWORD dwMemberID;
    DWORD dwValue;
    BYTE btFlags;
};

struct KTongUnionBaseData {
    DWORD dwValue;
    DWORD dwLeaderID;
    char szUnionName[10];
};

struct KUnionTongList {
    char szUnionName[10];
    DWORD dwLeaderID;
    BYTE btCount;
    DWORD arTongID[25];
};

struct KZhaoMuInfo {
    BYTE byQingXiang;
    BYTE byActivity[4];
    char szCustomText[128];
    BYTE byAutoAcceptLevel;
    BYTE byRefuseApplyLevel;
};

struct LocalDispatchMsgChannel {
    DWORD ChannelId;
    BYTE Cost;
    BYTE ChannelFlag;
    DWORD dwMsgInterval;
};

struct MEMBER_SELF_MIX_DATA {
    DWORD dwLWeekGoalOffer;
};

struct MIX_PROTOCOL_u {
    BYTE btData[1];
    DWORD dwData[1];
    char szReserve[128];
    BYTE _jxpad_0[128];   // trailing padding: this struct is not pack(1) upstream
};

struct MapIdIndexPair {
    int nMapId;
    short int nMapIndex;
};

struct PARTNER_CTRL_INFO_u {
    BYTE m_byCurPartnerIdx;
    BYTE m_byCurPartnerCallOut;
    BYTE m_byCurPartnerFollowOnly;
    BYTE _jxpad_0[1];   // trailing padding: this struct is not pack(1) upstream
};

struct PARTNER_SIMPLE_INFO_2_u {
    BYTE m_byInfo[2];
    WORD m_wInfo;
    BYTE _jxpad_0[2];   // trailing padding: this struct is not pack(1) upstream
};

struct PARTNER_SIMPLE_INFO_4_u {
    BYTE m_byInfo[4];
    WORD m_wInfo[2];
    DWORD m_dwInfo;
    BYTE _jxpad_0[4];   // trailing padding: this struct is not pack(1) upstream
};

struct POS {
    BYTE x;
    BYTE y;
};

struct QUERY_TASK_RESULT {
    int nTaskID;
    int nReward;
    int nTotalTime;
    int nRemainTime;
    char szKilleeName[32];
};

struct SALE_STORES_SHOP {
    int m_nBuyIdx;
    CurrencyType m_ctCurrencyType;
    int m_nScale;
    BOOL m_bDynamicShop;
    char m_szShopName[32];
};

struct SIMPLE_INFO_8_u {
    BYTE m_byInfo[8];
    WORD m_wInfo[4];
    DWORD m_dwInfo[2];
    BYTE _jxpad_0[8];   // trailing padding: this struct is not pack(1) upstream
};

struct SViewItemInfo {
    int m_nID;
    BYTE m_btPattern;
    WORD m_wDetail;
    WORD m_wParticur;
    BYTE m_btSeries;
    BYTE m_btLevel;
    BYTE m_btLuck;
    int m_MagicLevel[6];
    WORD m_wVersion;
    DWORD m_dwRandomSeed;
    BYTE m_btExParam0;
    BYTE m_btExParam1;
    DWORD m_ExpiredTime;
    DWORD m_dwLeftUsageTime;
    WORD wPlatinaMagicIdx[2];
    DWORD dwExchangeValue;
    DWORD dwFortuneValue;
};

struct TLeagueCallBackScript {
    int nResult;
    int nScriptFileID;
    char szFunction[32];
};

struct TLeagueDoScript {
    BYTE byScriptFileLen;
    BYTE byScriptFuncLen;
    BYTE byScriptParamLen;
    char szBuf[1];
};

struct TLeagueRoleInfo {
    DWORD dwJob;
    char szRoleName[32];
    DWORD dwBufSize;
    char szBuf[1];
};

struct TONG_FIGURE_MEMBER {
    DWORD dwTongID;
    BYTE btFigure;
    BYTE btCount;
    DWORD arydwMemberID[56];
};

struct TONG_ID_NAME {
    DWORD m_dwID;
    char m_szName[32];
};

struct TONG_MEMBER_ID_NAME {
    DWORD m_dwID;
    char m_szName[32];
};

struct TONG_MEMBER_INFO {
    DWORD m_dwTongID;
    DWORD m_dwMemberID;
    DWORD m_dwJoinTime;
    DWORD m_dwLevel;
    DWORD m_dwOffer;
    DWORD m_dwWeekGoalOffer;
    DWORD m_dwWeeklyOffer;
    DWORD m_dwMonthlyOffer;
    DWORD m_dwTotalOffer;
    char m_szTitle[32];
};

struct TONG_MEMBER_TASK {
    WORD wID;
    int nValue;
};

struct TONG_RECORD {
    DWORD dwRecordTime;
    char szRecordContent[64];
};

struct TONG_TASK {
    WORD wID;
    int nValue;
};

struct TONG_UNION_ID_NAME {
    BYTE m_btCount;
    DWORD m_dwLeaderID;
    char m_szName[32];
};

struct TONG_WEEKGOAL_INFO {
    DWORD dwTongID;
    BYTE btCurGoalLevel;
    BYTE btGoalLevel;
    BYTE btGoalLevel_L;
    BYTE btWeekDay;
    DWORD dwGoalType;
    DWORD dwGoalLevel;
    DWORD dwGoalTotal;
    DWORD dwGoalPlayer;
    DWORD dwFinished;
    DWORD dwTongPrize;
    DWORD dwMemberPrize;
    DWORD dwGoalType_L;
    DWORD dwGoalLevel_L;
    DWORD dwGoalTotal_L;
    DWORD dwGoalPlayer_L;
    DWORD dwFinished_L;
    DWORD dwTongPrize_L;
    DWORD dwMemberPrize_L;
};

struct TOneLeagueData {
    DWORD wLen;
    DWORD dwLeagueType;
    char szLeagueName[48];
    DWORD dwCreateTime;
    WORD wRoleCount;
    WORD wTaskDataOffSet;
    WORD wTaskDataBufSize;
    DWORD dwReserved1;
    DWORD dwReserved2;
    char szBuf[1];
};

struct TRoleList {
    char Name[32];
    INT64 nValue;
    int nSect;
    BYTE byGender;
    BYTE bySort;
};

struct TTm {
    int tm_sec;
    int tm_min;
    int tm_hour;
    int tm_mday;
    int tm_mon;
    int tm_year;
    int tm_wday;
    int tm_yday;
    int tm_isdst;
};

struct TongData_Tong {
    DWORD dwTongID;
};

struct TongExHeaderBase {
    WORD m_wTongExLength;
    WORD m_wTongExProtocol;
};

struct VIEW_OTHER_DETAIL_INFO {
    INT64 nExperienceFull;
    INT64 nExperience;
    INT64 nCurLevelExperience;
    int aiAttr[28];
    BYTE btRankId;
    BYTE btSeries;
    BYTE nAllowDetailDetectFlag;
    BYTE _jxpad_139[1];   // trailing padding: this struct is not pack(1) upstream
};

struct _DataPair {
    DWORD dwOffset;
    DWORD dwLen;
};

struct _OneFigure {
    WORD wOnline;
    WORD wAll;
};

struct _TaskValue {
    WORD wTaskID;
    int nTaskValue;
};

struct stall_itemprice {
    DWORD dwItemID;
    int nPrice;
};

struct stallprotocol_header {
    BYTE ProtocolType;
    WORD wProcotolSize;
    BYTE stallProtocolType;
};

struct tagArenaResult {
    WORD wTongIndex[2];
    BYTE byResult;
    char szComment[32];
};
typedef tagArenaResult ARENARESULT;

struct tagBULLETIN_CONTENT_DATA_ContentData_t {
    int nLen;
    char szContent[800];
};

struct tagBULLETIN_SUMMARY_DATA_SummaryData_t {
    char szSummary[64];
    char szDate[16];
};

struct tagChangeExtPoint_u {
    unsigned int uExtPointIndex;
    unsigned int uSilverType;
    BYTE _jxpad_0[4];   // trailing padding: this struct is not pack(1) upstream
};

struct tagExtPointInfo {
    int nExtPoint[8];
};

struct tagFOUNDRY_CLIENTSEND_NecItemPos_t {
    int nPlace;
    int nX;
    int nY;
};

struct tagKIB_ItemBuyInfo {
    char szAccount[32];
    int nPlayerDataIndex;
    int nGoodsIndex;
    int nItemTypeID;
    int nItemLevel;
    int nUseType;
    int nPrice;
    DWORD dwOverdueTime;
};

struct tagKIB_ItemBuyResult {
    char szAccount[32];
    int nPlayerDataIndex;
    int nGoodsIndex;
    int nItemTypeID;
    int nItemLevel;
    int nPrice;
    INT64 nItemGUID;
    int nRetCode;
};

struct tagKIB_ItemUseInfo {
    char szAccount[32];
    int nPlayerDataIndex;
    int nItemTypeID;
    int nItemLevel;
    INT64 nItemGUID;
};

struct tagKIB_ItemUseResult {
    char szAccount[32];
    int nPlayerDataIndex;
    int nItemTypeID;
    int nItemLevel;
    INT64 nItemGUID;
    int nRetCode;
};

struct tagNOTIFY_CLIENT_u {
    INT nStatus;
    CHAR cStatus[4];
    BYTE _jxpad_0[4];   // trailing padding: this struct is not pack(1) upstream
};

struct tagPLAYER_ALL_TASKVALUE_SYNC_TaskArray_t {
    int nTaskID;
    int nTaskValue;
};

struct tagProtocolHeader_u {
    BYTE cProtocol;
    BYTE ProtocolType;
    BYTE _jxpad_0[1];   // trailing padding: this struct is not pack(1) upstream
};

struct tagSKILL_SEND_ALL_SYNC_m_sAllSkill_t {
    WORD SkillId;
    BYTE CurLevel;
    BYTE MaxLevel;
    WORD SkillExp;
};

struct AUCTION_ADDPRICE_C2S : AUCTION_PROTOCOLHEADER {
    DWORD dwAuctionItemID;
    UINT uPriceNow;
    UINT uAddPriceTimes;
};

struct AUCTION_JOIN_C2S : AUCTION_PROTOCOLHEADER {
    DWORD dwAuctionItemID;
};

struct AUCTION_NOTIFY_S2C : AUCTION_PROTOCOLHEADER {
    char szMsg[1];
};

struct AUCTION_OPENSUBMIT_S2C : AUCTION_PROTOCOLHEADER {
};

struct AUCTION_PRICEINCREASE_S2C : AUCTION_PROTOCOLHEADER {
    UINT uAuctionItemID;
    UINT uPriceNow;
    char szPriceOwner[32];
    WORD nRemainTime;
};

struct AUCTION_QUITREQUEST_C2S : AUCTION_PROTOCOLHEADER {
    DWORD dwAuctionItemID;
};

struct AUCTION_QUIT_S2C : AUCTION_PROTOCOLHEADER {
};

struct AUCTION_RELAYHEADER_G2R : EXTEND_HEADER {
    char szRoleName[32];
    DWORD dwSubWorldID;
};

struct AUCTION_RELAYHEADER_R2G : EXTEND_HEADER {
    DWORD dwNameID;
};

struct AUCTION_SUBMITITEM_C2S : AUCTION_PROTOCOLHEADER {
    DWORD dwItemID;
    UINT uItemBasePrice;
    UINT uItemAddPricePerTime;
    UINT uPrearrangeRounds;
};

struct AuctionItemInfo : SViewItemInfo {
    UINT uItemAuctionID;
    UINT uPrice;
    UINT uAddPriceUnit;
};

struct BATTLE_RELAYHEADER_G2R : EXTEND_HEADER {
};

struct BATTLE_RELAYHEADER_R2G : EXTEND_HEADER {
};

struct C2S_TONG_CHECK_APPLYER_STATE_RESPOND : EXTEND_HEADER {
    DWORD dwTongID;
    BYTE byCurPageIndex;
    int nOperatorIndex;
    char szOperatorName[32];
    char szApplyerName[32];
    BOOL bResult;
    DWORD dwGSID;
};

struct CHAT_MSG_EX : EXTEND_HEADER {
    char m_szSourceName[32];
    char m_szAccountName[32];
    WORD SentenceLength;
};

struct CITYWAR_COMMONINPUT : CITYWAR_PROTOCOLHEADER {
    BYTE bIsNumberInput;
    char szTitle[32];
    int nMax;
    int nMin;
    char szInitString[32];
};

struct CITYWAR_COMMONINPUTNUMBER : CITYWAR_PROTOCOLHEADER {
    int nNumber;
};

struct CITYWAR_COMMONINPUTSTRING : CITYWAR_PROTOCOLHEADER {
    WORD wStrLen;
};

struct CITYWAR_OPENCITYMANAGE_S2C : CITYWAR_PROTOCOLHEADER {
    int nCityArea;
    DWORD dwExchangeTax;
    DWORD dwPriceParam;
};

struct CITYWAR_RELAYHEADER_G2R : EXTEND_HEADER {
};

struct CITYWAR_RELAYHEADER_R2G : EXTEND_HEADER {
};

struct CITYWAR_SUBMITCITYTAXRATES_C2S : CITYWAR_PROTOCOLHEADER, CITYWAR_TAXRATES {
    int nCityArea;
};

struct DISMISS_RELATION : EXTEND_HEADER {
    char RoleA[32];
    char RoleB[32];
    char Relation[32];
};

struct EXTEND_PASSTOBEVY : EXTEND_HEADER {
    WORD datasize;
    WORD playercount;
};

struct EXTEND_PASSTOSOMEONE : EXTEND_HEADER {
    DWORD nameid;
    long unsigned int lnID;
    WORD datasize;
};

struct FRIEND_ASSOCIATE : EXTEND_HEADER {
    BYTE bidir;
};

struct FRIEND_ASSOCIATEBEVY : EXTEND_HEADER {
};

struct FRIEND_STATE : EXTEND_HEADER {
    BYTE state;
};

struct GiveItemPos {
    BYTE nPlace;
    POS sPackPos;
    POS sUiPos;
};

struct KC2S_TONG_ACCEPT_OR_REFUSE : EXTEND_HEADER {
    DWORD dwTongID;
    BYTE byAccept;
    BYTE byCurPageIndex;
    int nOperatorIndex;
    char szOperatorName[32];
    char szPlayerName[32];
};

struct KC2S_TONG_ADD_TO_APPLY_LIST : EXTEND_HEADER {
    DWORD dwTongID;
    DWORD dwPlayerNameID;
    DWORD dwOfferBring;
    BYTE btSex;
    BYTE btLevel;
    char szPlayerName[32];
};

struct KC2S_TONG_GET_APPLY_LIST : EXTEND_HEADER {
    DWORD dwTongID;
    int nPlayerIndex;
    BYTE byPageIndex;
};

struct KC2S_TONG_SAVE_ZHAOMU_INFO : EXTEND_HEADER {
    DWORD dwTongID;
    KZhaoMuInfo ZhaoMuInfo;
};

struct KEMPIRE_HISTORY : KEMPIRE_DATA {
    DWORD dwEndTime;
};

struct KEMPIRE_INFO : KEMPIRE_DATA {
    char szSealOwner[32];
    DWORD dwTurnIdx;
};

struct KILLER_CANCELTASK : KILLER_PROTOCOLHEADER {
    int m_nTaskID;
};
typedef KILLER_CANCELTASK KILLER_TAKETASK;

struct KILLER_CANCELTASK_G2R : EXTEND_HEADER {
    int m_nTaskID;
    char szRoleName[32];
};
typedef KILLER_CANCELTASK_G2R KILLER_TAKETASK_G2R;

struct KILLER_CREATETASK : EXTEND_HEADER {
    int m_nRentFee;
    char m_chCreatorName[32];
    char m_chKilleeName[32];
    int m_nReward;
};

struct KILLER_CREATETASK_FAILED : EXTEND_HEADER {
    int m_nNameID;
    int m_nMoneyReturn;
};
typedef KILLER_CREATETASK_FAILED KILLER_CANCELTASK_R2G;

struct KILLER_GETMONEY : EXTEND_HEADER {
    int m_nTaskID;
};

struct KILLER_NOTIFY : KILLER_PROTOCOLHEADER {
    char szMsg[1];
};

struct KILLER_PK : EXTEND_HEADER {
    char m_chKillerName[32];
    char m_chKilleeName[32];
};

struct KILLER_QUERYRESULT_S2C : KILLER_PROTOCOLHEADER {
    int nResultCount;
    char chTaskState;
    QUERY_TASK_RESULT queryResult[1];
};

struct KILLER_QUERYTASK_G2R : EXTEND_HEADER {
    int m_nQueryType;
    char m_szQueryer[32];
};

struct KILLER_QUERYWISEMAN_C2S : KILLER_PROTOCOLHEADER {
    char szQueryTargetName[32];
};

struct KILLER_REPLYSCRIPT : EXTEND_HEADER {
    int m_nNameID;
    DWORD m_dwRewardTaskID;
    int m_nReward;
    DWORD m_dwCancelTaskID;
    int m_nCancelMoney;
    char m_nOwnTaskCount;
    char m_nMyTaskCount;
};

struct KILLER_SCRIPTASK : EXTEND_HEADER {
    char m_chRoleName[32];
};

struct KILLER_SUBMITTASK : KILLER_PROTOCOLHEADER {
    int m_nRentFee;
    char m_chKilleeName[32];
    int m_nReward;
};

struct KPROTOGR_DOSCRIPT : EXTEND_HEADER {
    BYTE byPathNameLen;
    BYTE byFuncNameLen;
    DWORD dwParamObjLen;
    DWORD dwCallBackScript;
    DWORD dwCallBackParam;
    BYTE byCallBackFuncLen;
};

struct KPROTOGR_NW_ENTHRONE : EXTEND_HEADER {
    char szName[32];
    char szTong[32];
    BYTE bySide;
    BYTE bySex;
};

struct KPROTOGR_NW_REMARKEMPEROR : EXTEND_HEADER {
    int nRemark;
};

struct KPROTOGR_NW_SETNATIONTITLE : EXTEND_HEADER {
    char szTitle[32];
};

struct KPROTOGR_NW_SETTASK : EXTEND_HEADER {
    DWORD dwIndex;
    DWORD dwValue;
};

struct KPROTORG_NW_AWARDEMPEROR : EXTEND_HEADER {
    DWORD dwExp;
};

struct KPROTORG_NW_CONGRATULATION : EXTEND_HEADER {
    char szWords[56];
    WORD wTimeout;
};

struct KPROTORG_NW_FORBIDCHAT : EXTEND_HEADER {
    char szName[32];
    int nTime;
};

struct KPROTORG_NW_LEVY : EXTEND_HEADER {
    int nAmount;
    int nMinLevel;
};

struct KPROTORG_NW_LEVYAMOUNT : EXTEND_HEADER {
    int nAmount;
};

struct KPROTORG_NW_SYNCNATIONTITLE : EXTEND_HEADER {
    char szTitle[32];
};

struct KPROTORG_NW_SYNCREMARK : EXTEND_HEADER {
    DWORD dwGoodness;
    DWORD dwBadness;
};

struct KPROTORG_NW_SYNCSEALOWNER : EXTEND_HEADER {
    char szOwner[32];
};

struct KPROTORG_NW_SYNCTASK : EXTEND_HEADER {
    WORD wCount;
};

struct KPROTORG_NW_TITLEUPDATE : EXTEND_HEADER {
    DWORD dwTongID;
    char szName[32];
};

struct KPROTORG_SCRIPTRESULT : EXTEND_HEADER {
    DWORD dwCallBackScript;
    DWORD dwCallBackParam;
    BYTE byCallBackFuncLen;
    DWORD dwResultLen;
};

struct KPROTO_DUNGEONMAP : EXTEND_HEADER {
    DWORD dwMapID;
    DWORD dwMapTempID;
    BOOL bNeedSave;
    BOOL bOccupy;
    BYTE byOper;
    BOOL bResult;
};

struct KPROTO_GS2R_SYNCEND : EXTEND_HEADER {
    char szAccount[32];
};

struct KREFUSE_APPLY_JOIN_TONG : EXTEND_HEADER {
    char szSrcName[32];
    char szTargetName[32];
};

struct KSYNC_TONG_APPLY_INFO : EXTEND_HEADER {
    WORD wLength;
    DWORD dwTongID;
    int nPlayerIndex;
    BYTE byPageIndex;
    BYTE byCount;
    KRET_APPLYINFO ApplyInfo[];
};

struct KSYNC_TONG_ZHAOMU_INFO : EXTEND_HEADER {
    DWORD dwTongID;
    KZhaoMuInfo ZhaoMuInfo;
};

struct KTongInfoEx : KTongInfo {
    WORD nRetireCount;
    DWORD dwBuildLevel;
    DWORD dwBuildFund;
    DWORD nCombatFund;
    DWORD dwStoredOffer;
    DWORD dwStoredBuildFund;
    DWORD nServiceFee;
    DWORD nStandFund;
    DWORD nWeekBuildFund;
    WORD nOnlineMemberCount;
    WORD nOnlineManagerCount;
    WORD nOnlineDirectorCount;
    BYTE nPauseState;
    BYTE nTongMap;
    WORD nDay;
    WORD nWeek;
    WORD wExTaskNum;
    _TaskValue TaskValue[1];
};

struct KTongListPageData {
    BYTE btSortType;
    WORD wSortCount;
    WORD wPageIndex;
    DWORD dwTime;
    BYTE btCount;
    KTongBaseData arData[25];
};

struct KTongMemberPageData {
    DWORD dwTongID;
    BYTE btSortType;
    BYTE btFilterFlag;
    WORD wSortCount;
    WORD wPageIndex;
    DWORD dwTime;
    BYTE btCount;
    KTongMemberBaseData arData[25];
};

struct KTongShowInfo {
    DWORD dwTongID;
    char szName[32];
    WORD wMemberCount;
    WORD wLevel;
    int nHuoYueDu;
    KZhaoMuInfo ZhaoMuInfo;
};

struct KTongUnionPageData {
    BYTE btSortType;
    WORD wSortCount;
    WORD wPageIndex;
    DWORD dwTime;
    BYTE btCount;
    KTongUnionBaseData arData[25];
};

struct LADDER_RELAYHEADER_G2R : EXTEND_HEADER {
    unsigned int ulLadderID;
    TRoleList RoleList;
};

struct LEAGUE_RELAYHEADER : EXTEND_HEADER {
    DWORD dwServiceMatchID;
};

struct OFFLINELIVE_CLAIM : EXTEND_HEADER {
    char szRole[32];
};

struct PLAYERCOMM_NOTIFYCHANNELID : EXTEND_HEADER {
    char channel[32];
    DWORD channelid;
    BYTE cost;
    BYTE channelType;
};

struct R2S_GET_TAGS_RESPOND : EXTEND_HEADER {
    char szSrcPlayer[32];
    char szTargetPlayer[32];
    WORD wDataSize;
    BYTE byData[];
};

struct R2S_QUERY_STAT_ID_RESPOND : EXTEND_HEADER {
    char szName[64];
    int nID;
};

struct RELAY_ASKWAY_DATA : EXTEND_HEADER {
    DWORD nFromIP;
    DWORD nFromRelayID;
    DWORD seekRelayCount;
    WORD seekMethod;
    WORD wMethodDataLength;
    WORD routeDateLength;
};

struct RELAY_CONNECT_READY : EXTEND_HEADER {
    BYTE btReady;
};

struct RELAY_DATA : EXTEND_HEADER {
    DWORD nToIP;
    DWORD nToRelayID;
    DWORD nFromIP;
    DWORD nFromRelayID;
    WORD routeDateLength;
};

struct RELAY_DYNMAP_CREAT_INFO : EXTEND_HEADER {
    DWORD dwMapID;
    BYTE btResult;
};

struct RELAY_DYNMAP_DELETE_RESULT : EXTEND_HEADER {
    DWORD dwMapID;
    BYTE btResult;
};

struct RELAY_LADDERDATA : EXTEND_HEADER {
    DWORD dwLadderID;
    BYTE btRoleCount;
    TRoleList StatData[10];
};

struct RELAY_PING : EXTEND_HEADER {
    DWORD dwSequence;
    DWORD dwTimestamp;
};

struct RELAY_QUERY_MAP : EXTEND_HEADER {
    DWORD dwServerID;
};

struct ROLENAME_CHANGE : EXTEND_HEADER {
    char szAccount[32];
    char szRoleName[32];
    char szOperName[32];
};

struct S2C_TONG_CHECK_APPLYER_STATE : EXTEND_HEADER {
    DWORD dwTongID;
    BYTE byCurPageIndex;
    int nOperatorIndex;
    char szOperatorName[32];
    char szApplyerName[32];
    DWORD dwGSID;
};

struct S2R_ADD_TAG_REQUEST : EXTEND_HEADER {
    char szSrcPlayer[32];
    char szTargetPlayer[32];
    char szTagTxt[32];
};

struct S2R_DEL_TAG_REQUEST : EXTEND_HEADER {
    char szPlayerName[32];
    time_t nTagTime;
};

struct S2R_GET_TAGS_REQUEST : EXTEND_HEADER {
    char szSrcPlayer[32];
    char szTargetPlayer[32];
};

struct S2R_QUERY_STAT_ID_REQUEST : EXTEND_HEADER {
    char szName[64];
};

struct S2R_SET_FRIEND_PUBLISH_FLAG : EXTEND_HEADER {
    char szPlayerName[32];
    BYTE byFlag;
};

struct S2R_SET_STAT_DATA_REQUEST : EXTEND_HEADER {
    char szName[64];
    int64_t nValue;
};

struct S2R_UPDATE_STAT_DATA_REQUEST : EXTEND_HEADER {
    int nCount;
    KSTAT_DATA_MODIFY Values[];
};

struct STALL_ADV_SYNC : stallprotocol_header {
    DWORD dwSellerID;
    int nAdvSize;
    char chAdv[1];
};

struct STALL_BUYINFO : stallprotocol_header {
    DWORD dwSellerID;
    DWORD dwItemID;
    int nX;
    int nY;
    int nPrice;
    int nDurability;
};

struct STALL_REQUEST : stallprotocol_header {
    DWORD nSellerID;
};

struct STALL_RETVALUE : stallprotocol_header {
    int nRetValue;
};

struct STALL_TAXRATE_SYNC : stallprotocol_header {
    int nTaxRate;
    int nTaxBase;
};

struct STALL_TRADE_SUCCESS : stallprotocol_header {
    char szBuyer[32];
    char szSellItemName[32];
};

struct STONG_ACCEPT_INSTATE_COMMAND : EXTEND_HEADER {
    DWORD m_dwParam;
    DWORD m_dwTongNameID;
    BYTE m_btOldFigure;
    BYTE m_btOldPos;
    BYTE m_btNewFigure;
    BYTE m_btNewPos;
    BYTE m_btAcceptFalg;
    char m_szName[32];
    char m_szOperater[32];
};

struct STONG_ACCEPT_MASTER_COMMAND : EXTEND_HEADER {
    DWORD m_dwParam;
    DWORD m_dwTongNameID;
    BYTE m_btFigure;
    BYTE m_btPos;
    BYTE m_btAcceptFalg;
    char m_szName[32];
};

struct STONG_ADD_MEMBER_COMMAND : EXTEND_HEADER {
    WORD m_wLength;
    DWORD m_dwPlayerNameID;
    DWORD m_dwParam;
    DWORD m_dwOfferBring;
    BYTE m_btSex;
    BYTE m_btLevel;
    char m_szOperatorName[32];
    BYTE m_btTongNameLength;
    BYTE m_btPlayerNameLength;
    char m_szBuffer[96];
};

struct STONG_ADD_TAX_COMMAND : EXTEND_HEADER {
    DWORD m_dwMoney;
    char m_szTongName[32];
};

struct STONG_APPLY_DISPENSE_COMMAND : EXTEND_HEADER {
    DWORD m_dwParam;
    DWORD m_dwNpcID;
    DWORD m_dwTongNameID;
    DWORD m_dwDirectorMoney;
    DWORD m_dwManagerMoney;
    DWORD m_dwMemberMoney;
    char m_szTongName[32];
    BYTE m_btIsAll;
};

struct STONG_APPLY_LEAVE_UNION_COMMAND : EXTEND_HEADER {
    DWORD m_dwParam;
    DWORD m_dwNpcID;
    DWORD m_dwTongNameID;
    BYTE m_btOpeID;
    char m_szOpeName[32];
    char m_szSelfTongName[32];
    char m_szTarTongName[32];
};

struct STONG_APPLY_UNION_INFO_COMMAND : EXTEND_HEADER {
    DWORD m_dwParam;
    DWORD m_dwNpcID;
    DWORD m_dwTongNameID;
    BYTE m_btApplyType;
};

struct STONG_BE_KICKED_SYNC : EXTEND_HEADER {
    DWORD m_dwParam;
    BYTE m_btFigure;
    BYTE m_btPos;
    char m_szName[32];
};

struct STONG_BILLBOARD_COMMAND : EXTEND_HEADER {
    DWORD m_dwParam;
};

struct STONG_BILLBOARD_SYNC : EXTEND_HEADER {
    WORD m_wLength;
    DWORD m_dwParam;
    DWORD m_dwMemberNum[10];
    BYTE m_btDataNum;
    BYTE m_btCamp[10];
    BYTE m_btNameLen[10];
    char m_szName[320];
};

struct STONG_CHANGE_AS_SYNC : EXTEND_HEADER {
    DWORD m_dwParam;
    DWORD m_dwTongNameID;
    BYTE m_btFigure;
    DWORD m_dwNameID;
    char m_szTitle[32];
    char m_szName[32];
};

struct STONG_CHANGE_EXP_COMMAND : EXTEND_HEADER {
    DWORD m_dwParam;
    DWORD m_dwTongNameID;
    BYTE m_btAddFlag;
    DWORD m_dwExp;
    char m_szName[32];
};

struct STONG_CHANGE_EXP_SYNC : EXTEND_HEADER {
    DWORD m_dwParam;
    BYTE m_btAddFlag;
    BYTE m_btSuccessFlag;
    DWORD m_dwTongNameID;
    DWORD m_dwExp;
    DWORD m_dwCurExp;
    DWORD m_dwCurLevel;
    char m_szName[32];
};

struct STONG_CHANGE_JOB_CALL_COMMAND : EXTEND_HEADER {
    DWORD m_dwParam;
    DWORD m_dwTongNameID;
    BYTE m_btFigure;
    DWORD m_dwMemberID;
    char m_szCall[32];
};

struct STONG_CHANGE_MASTER_COMMAND : EXTEND_HEADER {
    DWORD m_dwParam;
    DWORD m_dwTongNameID;
    BYTE m_btFigure;
    BYTE m_btPos;
    char m_szName[32];
};

struct STONG_CHANGE_MASTER_FAIL_SYNC : EXTEND_HEADER {
    DWORD m_dwParam;
    DWORD m_dwTongNameID;
    BYTE m_btFailID;
    char m_szName[32];
};

struct STONG_CHANGE_MASTER_SYNC : EXTEND_HEADER {
    DWORD m_dwTongNameID;
    char m_szName[32];
};

struct STONG_CHANGE_MONEY_SYNC : EXTEND_HEADER {
    DWORD m_dwParam;
    BYTE m_btSaveFlag;
    BYTE m_btSuccessFlag;
    DWORD m_dwTongNameID;
    DWORD m_dwMoneyFundChange;
    INT64 m_llMoneyFund;
    char m_szName[32];
};

struct STONG_CREATE_COMMAND : EXTEND_HEADER {
    WORD m_wLength;
    DWORD m_dwPlayerNameID;
    DWORD m_dwParam;
    BYTE m_btCamp;
    BYTE m_btSex;
    BYTE m_btLevel;
    BYTE m_btTongNameLength;
    BYTE m_btPlayerNameLength;
    DWORD m_dwOffer;
    char m_szBuffer[64];
};

struct STONG_CREATE_FAIL_SYNC : EXTEND_HEADER {
    DWORD m_dwPlayerNameID;
    DWORD m_dwParam;
    BYTE m_btFailID;
};

struct STONG_CREATE_UNION_COMMAND : EXTEND_HEADER {
    DWORD m_dwParam;
    DWORD m_dwNpcID;
    DWORD m_dwTongNameID;
    char m_szUnionName[32];
};

struct STONG_DISPENSE_ERROR_SYNC : EXTEND_HEADER {
    DWORD m_dwParam;
    DWORD m_dwNpcID;
    DWORD m_dwTongNameID;
    DWORD m_dwDirectorMoney;
    DWORD m_dwManagerMoney;
    DWORD m_dwMemberMoney;
    BYTE m_btErrorID;
    INT64 m_llMoneyFund;
};

struct STONG_GM_ADD_TIME_COMMAND : EXTEND_HEADER {
    char m_szTongName[32];
    char m_szRoleName[32];
    WORD m_wYear;
    BYTE m_btMonth;
    BYTE m_btDay;
};

struct STONG_GM_DISMISS_COMMAND : EXTEND_HEADER {
    char m_szTongName[32];
};

struct STONG_GM_SET_LEVEL_COMMAND : EXTEND_HEADER {
    char m_szTongName[32];
    BYTE m_btChangeMode;
    DWORD m_dwData;
};

struct STONG_GM_SET_MASTER_COMMAND : EXTEND_HEADER {
    char m_szTongName[32];
    char m_szMasterName[32];
};

struct STONG_HEADER_WITH_PARAM : EXTEND_HEADER {
    DWORD m_dwParam;
};

struct STONG_INSTATE_COMMAND : EXTEND_HEADER {
    DWORD m_dwParam;
    DWORD m_dwTongNameID;
    BYTE m_btCurFigure;
    BYTE m_btNewFigure;
    char m_szName[32];
    char m_szOperater[32];
};

struct STONG_KICK_SYNC : EXTEND_HEADER {
    DWORD m_dwParam;
    DWORD m_dwTongNameID;
    BYTE m_btSuccessFlag;
    BYTE m_btFigure;
    BYTE m_btPos;
    char m_szName[32];
};

struct STONG_LEAVE_COMMAND : EXTEND_HEADER {
    DWORD m_dwParam;
    DWORD m_dwTongNameID;
    BYTE m_btFigure;
    BYTE m_btPos;
    char m_szName[32];
};

struct STONG_LEAVE_SYNC : EXTEND_HEADER {
    DWORD m_dwParam;
    BYTE m_btSuccessFlag;
    char m_szName[32];
};

struct STONG_LEVEL_BILLBOARD_COMMAND : EXTEND_HEADER {
    DWORD m_dwParam;
};

struct STONG_LEVEL_BILLBOARD_SYNC : EXTEND_HEADER {
    WORD m_wLength;
    DWORD m_dwParam;
    DWORD m_dwExp[10];
    int m_nLevel[10];
    BYTE m_btDataNum;
    BYTE m_btCamp[10];
    BYTE m_btNameLen[10];
    char m_szName[320];
};

struct STONG_LOGIN_DATA_SYNC : EXTEND_HEADER {
    DWORD m_dwParam;
    char m_szName[32];
    BYTE m_btFlag;
    char m_szMate[32];
};

struct STONG_ROUTE_PACKAGE : EXTEND_HEADER {
    WORD RouteDataSize;
    WORD ClientCount;
};

struct STONG_SYSTEM_CHANGE_MONEY_COMMAND : EXTEND_HEADER {
    BYTE m_btSaveFlag;
    DWORD m_dwMoney;
    char m_szTongName[32];
};

struct STONG_SYSTEM_MOVE_EXP_COMMAND : EXTEND_HEADER {
    DWORD m_dwExp;
    char m_szGetExpTongName[32];
    char m_szSubExpTongName[32];
};

struct STONG_UNION_ADD_MEMBER_COMMAND : EXTEND_HEADER {
    DWORD m_dwAccepterID;
    DWORD m_dwApplyerID;
    DWORD m_dwUnionTong;
    DWORD m_dwMemberTong;
};

struct STONG_UNION_INFO_SYNC : EXTEND_HEADER {
    WORD m_wLength;
    DWORD m_dwParam;
    DWORD m_dwNpcID;
    BYTE m_btGetType;
    BYTE m_btFlag;
    BYTE m_btUnionFlag;
    BYTE m_btUnionLeader;
    BYTE m_btSelfCamp;
    BYTE m_btUnionCamp;
    BYTE m_btUnionNum;
    DWORD m_dwTongNameID;
    char m_szUnionName[32];
    BYTE m_btNameLength[10];
    char m_szUnionTongName[320];
};

struct StallViewItemInfo : SViewItemInfo {
    int nX;
    int nY;
    int nWidth;
    int nHeight;
    int nPrice;
    int m_nCurrentDur;
    int m_nMaxDurability;
};

struct TLeagueMemberData {
    DWORD dwLeagueType;
    char szLeagueName[48];
    TLeagueRoleInfo CoreData;
};

struct TModuleCfg_SyncToGS : EXTEND_HEADER {
    WORD wLen;
    WORD wCount;
    BYTE pBuffer[1];
};

struct TONGNAME_CHANGE : EXTEND_HEADER {
    char szOldTong[32];
    char szNewTong[32];
    char szOperName[32];
    int nPlayerIndex;
};

struct TONGNAME_QUERY : EXTEND_HEADER {
    char szTongName[32];
    char szOperName[32];
    int nPlayerIndex;
};

struct TONG_BASE {
    BYTE m_btCount;
    TONG_ID_NAME aryTongIDName[25];
};

struct TONG_FIGURE_COUNT {
    DWORD dwTongID;
    BYTE btMasterOnline;
    _OneFigure sCountDirector;
    _OneFigure sCountManager;
    _OneFigure sCountMember;
    _OneFigure sCountRetire;
};

struct TONG_MEMBER_BASE {
    DWORD m_dwTongID;
    BYTE m_btCount;
    TONG_MEMBER_ID_NAME aryMemberIDName[25];
};

struct TONG_RECORDLIST_INFO {
    DWORD dwTongID;
    WORD wRecordCount;
    TONG_RECORD aryRecord[100];
};

struct TONG_UNION_BASE {
    BYTE m_btCount;
    TONG_UNION_ID_NAME aryUnionIDName[25];
};

struct TSyncFiles_ToGS_Header : EXTEND_HEADER {
    DWORD dwFileListID;
    BYTE btOnlyForGS;
};

struct TongData_TongBuffer : TongData_Tong {
    DWORD dwDataLen;
    BYTE buffer[];
};

struct TongExProtocolRG : EXTEND_HEADER, TongExHeaderBase {
};

struct _OneWorkshop {
    DWORD dwWorkshopID;
    WORD wTypeID;
    BYTE btLevel;
    BYTE btUseLevel;
    BYTE btState;
    _TaskValue TaskValue[1];
};

struct _tagSyncFileHead : EXTEND_HEADER {
    BYTE _jxpad_2[2];   // padding the binary shows here
    _DataPair pairFileName;
    _DataPair pairFileData;
    DWORD dwCheckCode;
};

struct stall_stalllevelnotallow : stallprotocol_header {
    int nMinPlayerLevelAllowed;
};

struct stall_stallmarkprice : stallprotocol_header {
    int nCount;
    int nTaxRate;
    stall_itemprice arrStallPrice[1];
};

struct tagAccountUserInfo {
    tagExtPointInfo ExtPointInfo;
    DWORD nTotalLeftTime;
    DWORD nLeftTimeOfPoint;
    KACCOUNT_LIMITTIME_INFO LimitTimeInfo;
};

struct tagEnterGame2 : EXTEND_HEADER {
    char szAccount[32];
    char szRole[32];
    DWORD dwNameID;
    DWORD dwParam;
    long unsigned int lnID;
    BYTE byLevel;
};

struct tagLeaveGame2 : EXTEND_HEADER {
    BYTE cCmdType;
    char szAccount[32];
    char szRole[32];
};

struct tagMapArrangeNotify : EXTEND_HEADER {
    int nMapCount;
    MapIdIndexPair MapIdIndexList[1];
};

struct tagMapIDAssign : EXTEND_HEADER {
    int nMapCount;
    int nDynMapCount;
    DWORD aMapID[1];
};

struct tagProtocolHeader {
    union {
        BYTE cProtocol;
        BYTE ProtocolType;
    };
};

struct tagRelaySDBRecord : EXTEND_HEADER {
    unsigned int uKeyParam1;
    unsigned int uKeyParam2;
    unsigned char byKeyStringLen;
    unsigned char byFlag;
    short unsigned int uDataBufferLen;
    unsigned char byOperParam;
};

struct tagRelayStatAutoHangPlayer : EXTEND_HEADER {
    int nSubWorldID;
    int nPlayerCount;
    int nAutoHangPlayerCount;
};

struct tagRelayToGameSvrTestMsg : EXTEND_HEADER {
    BYTE bMsgLen;
    int nReserved[2];
    char sMsg[1];
};

struct AUCTION_ADDPRICE_G2R : AUCTION_RELAYHEADER_G2R {
    DWORD dwAuctionItemID;
    UINT uPriceNow;
    UINT uAddPriceTimes;
    DWORD dwPlayerMoney;
};

struct AUCTION_GETFAILEDITEM_G2R : AUCTION_RELAYHEADER_G2R {
    DWORD dwAuctionItemID;
};

struct AUCTION_GETSALEMONEY_G2R : AUCTION_RELAYHEADER_G2R {
    DWORD dwAuctionItemID;
};

struct AUCTION_ITEMINFO_S2C : AUCTION_PROTOCOLHEADER {
    BYTE bQueryQueue;
    UINT uResultCount;
    AuctionItemInfo sItems[];
};

struct AUCTION_JOIN_G2R : AUCTION_RELAYHEADER_G2R {
    DWORD dwAuctionItemID;
    DWORD dwPlayerMoney;
};

struct AUCTION_QUERYITEMINFO_G2R : AUCTION_RELAYHEADER_G2R {
    BYTE bQueryQueue;
};

struct AUCTION_QUERYLADDER_G2R : AUCTION_RELAYHEADER_G2R {
};

struct AUCTION_QUITREQUEST_G2R : AUCTION_RELAYHEADER_G2R {
    DWORD dwAuctionItemID;
};

struct AUCTION_REPLYSCRIPTASK_R2G : AUCTION_RELAYHEADER_R2G {
    BYTE bState;
    BYTE bHasAutionNow;
    BYTE bSystemFull;
    DWORD dwAuctionID;
};

struct AUCTION_RETURNITEM_R2G : AUCTION_RELAYHEADER_R2G {
    SViewItemInfo theItem;
};

struct AUCTION_RETURNMONEY_R2G : AUCTION_RELAYHEADER_R2G {
    UINT uTheMoney;
};

struct AUCTION_SCRIPTASK_G2R : AUCTION_RELAYHEADER_G2R {
};

struct AUCTION_SUBMITITEMALLOWED_R2G : AUCTION_RELAYHEADER_R2G {
    DWORD dwItemID;
    DWORD dwAuctionItemID;
    DWORD dwCostMoney;
};

struct AUCTION_SUBMITITEM_REQUEST_G2R : AUCTION_RELAYHEADER_G2R {
    DWORD dwItemID;
    UINT uItemBasePrice;
    UINT uItemAddPricePerTime;
    UINT uPrearrangeRounds;
};

struct AUCTION_SUBMIT_ITEM_G2R : AUCTION_RELAYHEADER_G2R {
    DWORD dwAuctionItemID;
    SViewItemInfo item;
};

struct AUCTION_TRADERESULT_G2R : AUCTION_RELAYHEADER_G2R {
    DWORD dwAuctionItemID;
    BYTE bResult;
};

struct AUCTION_TRADE_R2G : AUCTION_RELAYHEADER_R2G {
    DWORD dwAuctionItemID;
    AuctionItemInfo theItem;
};

struct AuctionLadderItemInfo : AuctionItemInfo {
    char sAuctioner[32];
    char sBuyer[32];
};

struct BATTLE_NEW_ROUND_R2G : BATTLE_RELAYHEADER_R2G {
    WORD m_wBattleID;
    WORD m_wBattleLevel;
    WORD m_wIssueID;
    WORD m_wRoundCount;
    char m_strBattleName[32];
    WORD m_wWorldMapID;
    char m_strMapName[32];
    WORD m_wRuleType;
    char m_arystrRuleData[20][32];
};

struct BATTLE_ROUND_RESULT_G2R : BATTLE_RELAYHEADER_G2R {
    WORD m_wBattleID;
    WORD m_wBattleLevel;
    WORD m_wIssueID;
    WORD m_wRoundCount;
    BYTE m_btResult;
    BYTE _jxpad_11[1];   // trailing padding: this struct is not pack(1) upstream
};

struct C2S_ADD_TAG : tagProtocolHeader {
    char szTargetPlayer[32];
    char szTagTxt[32];
};

struct C2S_DEL_TAG : tagProtocolHeader {
    time_t nTagTime;
};

struct C2S_GET_TAGS_REQUEST : tagProtocolHeader {
    char szTargetPlayer[32];
};

struct C2S_SET_FRIEND_PUBLISH_FLAG : tagProtocolHeader {
    BYTE byCanPublishFlag;
};

struct C2S_SYNCEND : tagProtocolHeader {
    DWORD dwInitKey;
    DWORD dwProcessId;
};

struct CHATROOM_C2S_HEAD : tagProtocolHeader {
    WORD nMsgLen;
    BYTE nCmd;
};

struct CHATROOM_HEAD : tagProtocolHeader {
    BYTE nCmd;
};

struct CHATROOM_S2C_HEAD : tagProtocolHeader {
    WORD nMsgLen;
    BYTE nCmd;
};

struct CHAT_NPCCHAT : tagProtocolHeader {
    DWORD dwNpcId;
    WORD wMsgLen;
};

struct CITYWAR_ARENARESULT_G2R : CITYWAR_RELAYHEADER_G2R {
    int nCityArea;
    ARENARESULT arResult;
};

struct CITYWAR_MSG2PLAYER_R2G : CITYWAR_RELAYHEADER_R2G {
    DWORD dwPlayerNameID;
    WORD wSenLen;
};

struct CITYWAR_REPLYBULLETIN_R2G : CITYWAR_RELAYHEADER_R2G {
    DWORD dwPlayerNameID;
    WORD wSentenceLen;
};

struct CITYWAR_SCRIPTQUERYBULLETIN_G2R : CITYWAR_RELAYHEADER_G2R {
    char szPlayerName[32];
};

struct CITYWAR_SIGNUP_G2R : CITYWAR_RELAYHEADER_G2R {
    int nCityArea;
    char szPlayerName[32];
    char szTongName[32];
    DWORD dwSignUpFee;
};

struct CITYWAR_SUBMITCITYTAXRATES_G2R : CITYWAR_RELAYHEADER_G2R, CITYWAR_TAXRATES {
    int nCityArea;
    char szPlayerName[32];
    char szTongName[32];
};

struct CITYWAR_TONGACTION_G2R : CITYWAR_RELAYHEADER_G2R {
    BYTE nAction;
    int nCityArea;
    BYTE szTongName[32];
};

struct CITYWAR_TONGINFOSYNC_R2G : CITYWAR_RELAYHEADER_R2G {
    char szTongName[32];
    GSTongInfo sTongInfo;
};

struct CITYWAR_WARRESULT_G2R : CITYWAR_RELAYHEADER_G2R {
    int nCityArea;
    BYTE byResult;
};

struct ITEM_BIND_SYNC : tagProtocolHeader {
    DWORD m_dwID;
    int m_nBindState;
};

struct KACCOUNT_INFO2 : tagAccountUserInfo {
    tagExtPointInfo ChangePointInfo;
};

struct KPLAYER_LIMITTIME_SYNC : tagProtocolHeader {
    DWORD dwLimitTimeFlag;
    DWORD dwLimitTimeOnlineSeconds;
    DWORD dwLimitTimeOfflineSeconds;
};

struct KPROTORG_NW_POSITIONCHANGE : KPROTORG_NW_TITLEUPDATE {
    BYTE byInstate;
    BYTE byPosition;
};
typedef KPROTORG_NW_POSITIONCHANGE KPROTOGR_NW_POSITIONCHANGE;

struct KPROTORG_NW_SYNCEMPEROR : EXTEND_HEADER {
    KEMPIRE_INFO sInfo;
};

struct KPROTORG_NW_SYNCHISTORY : EXTEND_HEADER {
    KEMPIRE_HISTORY sHistory;
};

struct KPROTO_S2C_TMPCAMP : tagProtocolHeader {
    DWORD dwID;
    DWORD dwTmpCamp;
};

struct KPROTO_SYNCBALANCE : tagProtocolHeader {
    BYTE byType;
    DWORD dwBalance;
};

struct KPROTO_SYNCRESIST : tagProtocolHeader, KRESIST_ATTR {
    BYTE bySkillMaxLevelAddons;
};

struct KREQUEST_TONG_ZHAOMU_APPLY_JOIN : tagProtocolHeader {
    WORD m_wLength;
    BYTE m_btMsgId;
    DWORD m_dwTongID;
};

struct KREQUEST_TONG_ZHAOMU_PAGE_REQUEST : tagProtocolHeader {
    WORD m_wLength;
    BYTE m_btMsgId;
    int m_nPageIndex;
};

struct KREQUEST_TONG_ZHAOMU_REQUEST : tagProtocolHeader {
    WORD m_wLength;
    BYTE m_btMsgId;
    DWORD dwTongID;
};

struct KSAVE_TONG_ZHAOMU_REQUEST : tagProtocolHeader {
    WORD m_wLength;
    BYTE m_btMsgId;
    DWORD dwTongID;
    KZhaoMuInfo ZhaoMuInfo;
};

struct KSYNC_ID_ZHAOMU_APPLY_INFO : tagProtocolHeader {
    WORD m_wLength;
    BYTE m_btMsgId;
    BYTE byPageIndex;
    BYTE byCount;
    KRET_APPLYINFO ApplyInfo[];
};

struct KSYNC_TONG_ZHAOMU_PAGE_TO_CLIENT : tagProtocolHeader {
    WORD m_wLength;
    BYTE m_btMsgId;
    BYTE byPageIndex;
    KTongShowInfo ShowInfo[4];
};

struct KSYNC_TONG_ZHAOMU_TO_CLIENT : tagProtocolHeader {
    WORD m_wLength;
    BYTE m_btMsgId;
    DWORD dwTongID;
    KZhaoMuInfo ZhaoMuInfo;
};

struct KZHAOMU_ACCEPT_OR_REFUSE : tagProtocolHeader {
    WORD m_wLength;
    BYTE m_btMsgId;
    BYTE m_byAccept;
    BYTE m_byCurPageIndex;
    char szName[32];
};

struct KZHAOMU_GET_APPLY_INFO : tagProtocolHeader {
    WORD m_wLength;
    BYTE m_btMsgId;
    BYTE m_byPageIndex;
};

struct NPC_FEATURE_SYNC : tagProtocolHeader {
    DWORD m_dwNpcID;
    BYTE m_btFeaturePriority;
    BYTE m_btFeatureState;
    DWORD m_dwNpcSettingIdx;
    WORD m_wHelmType;
    WORD m_wArmorType;
    WORD m_wWeaponType;
    WORD m_wHorseType;
    WORD m_wMantleType;
    BYTE m_btChangeFeatureCount;
};

struct NPC_RUN_COMMAND : tagProtocolHeader {
    int nMpsX;
    int nMpsY;
    DWORD dwCheckValue;
};

struct NPC_SKILL_COMMAND : tagProtocolHeader {
    int nMpsY;
    int nSkillID;
    int nMpsX;
    DWORD dwCheckValue;
};

struct NPC_WALK_COMMAND : tagProtocolHeader {
    int nMpsX;
    int nMpsY;
    DWORD dwCheckValue;
};

struct PLAYER_NORMAL_SYNC : tagProtocolHeader {
    DWORD ID;
    BYTE AttackSpeed;
    BYTE RunSpeed;
    BYTE m_btChangeFeatureCount;
    BYTE HelmType;
    BYTE HorseType;
    BYTE WalkSpeed;
    BYTE CastSpeed;
    BYTE ArmorType;
    BYTE WeaponType;
    BYTE byMantleType;
    BYTE m_btSomeFlag1;
    BYTE m_btSomeFlag;
    WORD m_wTitleID;
    DWORD m_dwTongNameID;
    BYTE nFortuneRank;
};

struct PLAYER_SELECTUI_COMMAND : tagProtocolHeader {
    int nSelectIndex;
    int nSelectType;
    int nParam1;
    int nParam2;
};

struct PLAYER_SEND_CHAT_DATA_COMMAND : tagProtocolHeader {
    WORD m_wLength;
    BYTE m_btCurChannel;
    BYTE m_btType;
    BYTE m_btChatPrefixLen;
    WORD m_wSentenceLen;
    DWORD m_dwTargetID;
    int m_nTargetIdx;
    char m_szSentence[272];
};
typedef PLAYER_SEND_CHAT_DATA_COMMAND PLAYER_SEND_CHAT_COMMAND;

struct PLAYER_SEND_CHAT_DATA_SYNC : tagProtocolHeader {
    WORD m_wLength;
    BYTE m_btCurChannel;
    BYTE m_btNameLen;
    BYTE m_btChatPrefixLen;
    WORD m_wSentenceLen;
    DWORD m_dwSourceID;
    char m_szSentence[304];
};
typedef PLAYER_SEND_CHAT_DATA_SYNC PLAYER_SEND_CHAT_SYNC;

struct ROLENAME_CHANGE_RESULT : ROLENAME_CHANGE {
    BYTE nResult;
};

struct S2C_GET_TAGS_RESPOND : tagProtocolHeader {
    char szTargetPlayer[32];
    WORD wDataLen;
    BYTE byData[];
};

struct SIMPLE_INFO_8 : tagProtocolHeader {
    union {
        BYTE m_byInfo[8];
        WORD m_wInfo[4];
        DWORD m_dwInfo[2];
    };
};

struct SPECTATOR_MSG : tagProtocolHeader {
    WORD wLen;
    BYTE nCmd;
};

struct STALL_ITEMINFO_SYNC : stallprotocol_header {
    DWORD dwSellerID;
    int nItemCount;
    StallViewItemInfo arrItemInfo[1];
};

struct STONG_BE_INSTATED_SYNC : STONG_HEADER_WITH_PARAM {
    BYTE m_btFigure;
    BYTE m_btPos;
    char m_szTitle[32];
    char m_szName[32];
};

struct STONG_CHANGE_JOB_CALL_SYNC : STONG_HEADER_WITH_PARAM {
    BYTE m_btFigure;
    DWORD m_dwMemberID;
    BYTE m_btBroadcastFlag;
    DWORD m_dwTongNameID;
    char m_szCall[32];
};

struct STONG_CHANGE_WAR_STATE_SYNC : STONG_HEADER_WITH_PARAM {
    DWORD m_dwTongNameID;
    BYTE m_btWarState;
    BYTE m_btParam1;
    BYTE m_btParam2;
    BYTE m_btParam3;
};

struct STONG_CHECK_GET_MASTER_POWER_SYNC : STONG_HEADER_WITH_PARAM {
    BYTE m_btFigure;
    BYTE m_btPos;
    DWORD m_dwTongNameID;
    char m_szName[32];
};

struct STONG_CHECK_INSTATE_POWER_SYNC : STONG_HEADER_WITH_PARAM {
    BYTE m_btOldFigure;
    BYTE m_btOldPos;
    BYTE m_btNewFigure;
    BYTE m_btNewPos;
    DWORD m_dwTongNameID;
    char m_szName[32];
    char m_szOperater[32];
};

struct STONG_DISMISS_SYNC : STONG_HEADER_WITH_PARAM {
    DWORD m_dwTongNameID;
    char m_szName[32];
};

struct STONG_DISPENSE_SYNC : STONG_HEADER_WITH_PARAM {
    DWORD m_dwTongNameID;
    DWORD m_dwDirectorMoney;
    DWORD m_dwManagerMoney;
    DWORD m_dwMemberMoney;
    BYTE m_btFigure;
    char m_szName[32];
};

struct STONG_INSTATE_SYNC : STONG_HEADER_WITH_PARAM {
    DWORD m_dwTongNameID;
    BYTE m_btSuccessFlag;
    BYTE m_btSomeFlag;
    BYTE m_btOldFigure;
    BYTE m_btNewFigure;
    BYTE m_btParamType;
    char m_szTitle[32];
    char m_szName[32];
};

struct TDbDataBlock : tagProtocolHeader {
    WORD wProtocolSize;
    BYTE byStartFlag;
    DWORD dwDataLen;
    BYTE buf[800];
};

struct TGS2B_ReadyState : tagProtocolHeader {
    BYTE bReady;
};

struct THostExchange : tagProtocolHeader {
    char szAccount[32];
    BYTE nCommand;
    DWORD dwMapId;
};

struct TLeagueDoScriptCB : LEAGUE_RELAYHEADER {
    DWORD dwLeagueType;
    char szLeagueName[48];
    char szRoleName[48];
    TLeagueCallBackScript callScript;
    TLeagueDoScript doScript;
};

struct TLeagueMemberDataCB : LEAGUE_RELAYHEADER {
    TLeagueCallBackScript callScript;
    TLeagueMemberData CoreData;
};

struct TLeagueMemberTaskCB : LEAGUE_RELAYHEADER {
    DWORD dwLeagueType;
    char szLeagueName[48];
    char szRoleName[48];
    BYTE byIsAppendType;
    WORD wTaskID;
    int nTaskValue;
    TLeagueCallBackScript callScript;
};

struct TLeagueTaskCB : LEAGUE_RELAYHEADER {
    DWORD dwLeagueType;
    char szLeagueName[48];
    BYTE byIsAppendType;
    WORD wTaskID;
    int nTaskValue;
    TLeagueCallBackScript callScript;
};

struct TModuleCfg_SyncToClient : tagProtocolHeader {
    WORD wLen;
    WORD wCount;
    BYTE pBuffer[1];
};

struct TONGNAME_CHANGE_RESULT : TONGNAME_CHANGE {
    BYTE nResult;
};

struct TONGNAME_QUERY_RESULT : TONGNAME_QUERY {
    BYTE nResult;
};

struct TONG_WORKSHOP_INFO {
    DWORD dwTongID;
    WORD wCount;
    WORD nTaskValue;
    _OneWorkshop sWorkshops[1];
};

struct TOneLeagueDataCB : LEAGUE_RELAYHEADER {
    TLeagueCallBackScript callScript;
    TOneLeagueData CoreData;
};

struct TRADE_APPLY_START_COMMAND : tagProtocolHeader {
    DWORD m_dwID;
    DWORD dwCheckValue;
};

struct TRADE_REPLY_START_COMMAND : tagProtocolHeader {
    BYTE m_bDecision;
    int m_nDestIdx;
    DWORD dwCheckValue;
};

struct TRemoveLeagueCB : LEAGUE_RELAYHEADER {
    DWORD dwLeagueType;
    char szLeagueName[48];
    TLeagueCallBackScript callScript;
};

struct TRemoveLeagueMemberCB : LEAGUE_RELAYHEADER {
    DWORD dwLeagueType;
    char szLeagueName[48];
    char szRoleName[48];
    BYTE byRemoveLeagueWhenOnlyOneMember;
    TLeagueCallBackScript callScript;
};

struct TRoleInstance : tagProtocolHeader {
    char szRole[32];
    int nIndex;
    unsigned int nIdentity;
};

struct TRoleNameChange : tagProtocolHeader {
    char szAccount[32];
    char szRoleName[32];
    char szOperName[32];
};

struct TRoleNameQuery : tagProtocolHeader {
    char szAccount[32];
    char szRoleName[32];
    char szOperName[32];
    int nPlayerIndex;
};

struct TSaveRoleResult : tagProtocolHeader {
    long unsigned int ulIdentity;
    char szRole[32];
    int nResult;
};

struct TSelectDiceItem : tagProtocolHeader {
    DWORD dwDiceId;
    DWORD dwItemId;
    int nSelectType;
};

struct TSendBuf : TongExProtocolRG {
    BYTE data[];
};

struct TSyncFiles_ClientApplySync : tagProtocolHeader {
    DWORD dwFileListID;
    DWORD dwVerifyCode;
};

struct TSyncFiles_SyncToClient : tagProtocolHeader {
    DWORD dwLen;
    DWORD dwFileListID;
    BYTE pBuffer[1];
};

struct TSyncFiles_ToClient_Header : tagProtocolHeader {
    WORD wLen;
    DWORD dwFileListID;
};

struct TUnlockAccount : tagProtocolHeader {
    char szAccount[32];
};

struct TongExProtocolGC : tagProtocolHeader, TongExHeaderBase {
};

struct tagBOX_INFO_SYNC : tagProtocolHeader {
    BYTE byGainState;
    BYTE byBoxPasswordParam;
    BYTE byParam;
    BYTE byParam1;
};
typedef tagBOX_INFO_SYNC BOX_INFO_SYNC;

struct tagBOX_OPERATE_COMMAND : tagProtocolHeader {
    BYTE byOperate;
    DWORD dwParam1;
    DWORD dwParam2;
    DWORD Reserved;
};
typedef tagBOX_OPERATE_COMMAND BOX_OPERATE_COMMAND;

struct tagBULLETIN_CONTENT_DATA : tagProtocolHeader {
    WORD wSize;
    tagBULLETIN_CONTENT_DATA_ContentData_t ContentData;
};
typedef tagBULLETIN_CONTENT_DATA BULLETIN_CONTENT_DATA;

struct tagBULLETIN_CONTENT_QUERY : tagProtocolHeader {
    CHAR strDate[16];
};
typedef tagBULLETIN_CONTENT_QUERY BULLETIN_CONTENT_QUERY;

struct tagBULLETIN_SUMMARY_DATA : tagProtocolHeader {
    INT Count;
    tagBULLETIN_SUMMARY_DATA_SummaryData_t SummaryData[12];
};
typedef tagBULLETIN_SUMMARY_DATA BULLETIN_SUMMARY_DATA;

struct tagBotClientCheck : tagProtocolHeader {
    WORD wVersion;
    WORD wReserved;
    unsigned int uOffset;
    unsigned int uLength;
};

struct tagBotClientCheckResult : tagProtocolHeader {
    WORD wVersion;
    WORD wReserved;
    int nKey;
};

struct tagCHAT_ADD_FRIEND_COMMAND : tagProtocolHeader {
    int m_nTargetPlayerIdx;
};
typedef tagCHAT_ADD_FRIEND_COMMAND CHAT_ADD_FRIEND_COMMAND;

struct tagCHAT_ADD_FRIEND_FAIL_SYNC : tagProtocolHeader {
    int m_nTargetPlayerIdx;
};
typedef tagCHAT_ADD_FRIEND_FAIL_SYNC CHAT_ADD_FRIEND_FAIL_SYNC;

struct tagCHAT_ADD_FRIEND_SYNC : tagProtocolHeader {
    DWORD m_dwID;
    int m_nIdx;
    char m_szName[32];
};
typedef tagCHAT_ADD_FRIEND_SYNC CHAT_ADD_FRIEND_SYNC;

struct tagCHAT_APPLY_ADD_FRIEND_COMMAND : tagProtocolHeader {
    WORD m_wLength;
    DWORD m_dwTargetNpcID;
    char m_szInfo[256];
};
typedef tagCHAT_APPLY_ADD_FRIEND_COMMAND CHAT_APPLY_ADD_FRIEND_COMMAND;

struct tagCHAT_APPLY_ADD_FRIEND_SYNC : tagProtocolHeader {
    int m_nSrcPlayerIdx;
    char m_szSourceName[32];
    char m_szInfo[256];
};
typedef tagCHAT_APPLY_ADD_FRIEND_SYNC CHAT_APPLY_ADD_FRIEND_SYNC;

struct tagCHAT_APPLY_SEND_ONE_FRIEND_NAME_COMMAND : tagProtocolHeader {
    DWORD m_dwID;
};
typedef tagCHAT_APPLY_SEND_ONE_FRIEND_NAME_COMMAND CHAT_APPLY_SEND_ONE_FRIEND_NAME_COMMAND;

struct tagCHAT_CHANNELCHAT_HEAD : tagProtocolHeader {
};

struct tagCHAT_CHANNELCHAT_SYNC : tagProtocolHeader {
    WORD wSize;
    DWORD packageID;
    char someone[32];
    DWORD channelid;
    BYTE sentlen;
};
typedef tagCHAT_CHANNELCHAT_SYNC CHAT_CHANNELCHAT_SYNC;

struct tagCHAT_DELETE_FRIEND_COMMAND : tagProtocolHeader {
    DWORD m_dwID;
};
typedef tagCHAT_DELETE_FRIEND_COMMAND CHAT_DELETE_FRIEND_COMMAND;

struct tagCHAT_DELETE_FRIEND_SYNC : tagProtocolHeader {
    DWORD m_dwID;
};
typedef tagCHAT_DELETE_FRIEND_SYNC CHAT_DELETE_FRIEND_SYNC;

struct tagCHAT_EVERYONE : tagProtocolHeader {
    WORD wSize;
    WORD wChatLength;
};
typedef tagCHAT_EVERYONE CHAT_EVERYONE;

struct tagCHAT_FRIEND_OFFLINE_SYNC : tagProtocolHeader {
    DWORD m_dwID;
};
typedef tagCHAT_FRIEND_OFFLINE_SYNC CHAT_FRIEND_OFFLINE_SYNC;

struct tagCHAT_FRIEND_ONLINE_SYNC : tagProtocolHeader {
    DWORD m_dwID;
    int m_nPlayerIdx;
};
typedef tagCHAT_FRIEND_ONLINE_SYNC CHAT_FRIEND_ONLINE_SYNC;

struct tagCHAT_GROUPMAN : tagProtocolHeader {
    WORD wSize;
    WORD wChatLength;
    BYTE byHasIdentify;
    WORD wPlayerCount;
    BYTE channelType;
};
typedef tagCHAT_GROUPMAN CHAT_GROUPMAN;

struct tagCHAT_LOCAL_CHANNEL : tagProtocolHeader {
    WORD ChannelCount;
    LocalDispatchMsgChannel ChannelInfo[1];
};
typedef tagCHAT_LOCAL_CHANNEL CHAT_LOCAL_CHANNEL;

struct tagCHAT_LOGIN_FRIEND_NAME_SYNC : tagProtocolHeader {
    WORD m_wLength;
    DWORD m_dwID;
    int m_nPlayerIdx;
    char m_szName[32];
};
typedef tagCHAT_LOGIN_FRIEND_NAME_SYNC CHAT_LOGIN_FRIEND_NAME_SYNC;

struct tagCHAT_LOGIN_FRIEND_NONAME_SYNC : tagProtocolHeader {
    DWORD m_dwID;
    int m_nPlayerIdx;
};
typedef tagCHAT_LOGIN_FRIEND_NONAME_SYNC CHAT_LOGIN_FRIEND_NONAME_SYNC;

struct tagCHAT_ONE_FRIEND_DATA_SYNC : tagProtocolHeader {
    DWORD m_dwID;
    int m_nPlayerIdx;
    char m_szName[32];
};
typedef tagCHAT_ONE_FRIEND_DATA_SYNC CHAT_ONE_FRIEND_DATA_SYNC;

struct tagCHAT_REDELETE_FRIEND_COMMAND : tagProtocolHeader {
    DWORD m_dwID;
};
typedef tagCHAT_REDELETE_FRIEND_COMMAND CHAT_REDELETE_FRIEND_COMMAND;

struct tagCHAT_REFUSE_FRIEND_COMMAND : tagProtocolHeader {
    int m_nTargetPlayerIdx;
};
typedef tagCHAT_REFUSE_FRIEND_COMMAND CHAT_REFUSE_FRIEND_COMMAND;

struct tagCHAT_REFUSE_FRIEND_SYNC : tagProtocolHeader {
    WORD m_wLength;
    char m_szName[32];
};
typedef tagCHAT_REFUSE_FRIEND_SYNC CHAT_REFUSE_FRIEND_SYNC;

struct tagCHAT_RELEGATE : tagProtocolHeader {
    WORD wSize;
    DWORD nFromIP;
    DWORD nFromRelayID;
    DWORD channelid;
    BYTE TargetCls;
    DWORD TargetID;
    WORD routeDateLength;
};
typedef tagCHAT_RELEGATE CHAT_RELEGATE;

struct tagCHAT_SCREENSINGLE_ERROR_SYNC : tagProtocolHeader {
    WORD m_wLength;
    BYTE m_btError;
    char m_szName[32];
};
typedef tagCHAT_SCREENSINGLE_ERROR_SYNC CHAT_SCREENSINGLE_ERROR_SYNC;

struct tagCHAT_SET_CHANNEL_COMMAND : tagProtocolHeader {
    DWORD m_dwTakeChannel;
};
typedef tagCHAT_SET_CHANNEL_COMMAND CHAT_SET_CHANNEL_COMMAND;

struct tagCHAT_SOMEONECHAT_CMD : tagProtocolHeader {
    WORD wSize;
    DWORD packageID;
    char someone[32];
    BYTE sentlen;
};
typedef tagCHAT_SOMEONECHAT_CMD CHAT_SOMEONECHAT_CMD;

struct tagCHAT_SPECMAN : tagProtocolHeader {
    WORD wSize;
    DWORD nameid;
    long unsigned int lnID;
    WORD wChatLength;
};
typedef tagCHAT_SPECMAN CHAT_SPECMAN;

struct tagCHAT_TEST_MSG : tagProtocolHeader {
    BYTE bMsgLen;
    DWORD Reserved[2];
    char sMsg[1];
};
typedef tagCHAT_TEST_MSG CHAT_TEST_MSG;

struct tagCLEAR_TONG_CLAIMWAR_SYNC : tagProtocolHeader {
    WORD m_wLength;
    BYTE m_btMsgId;
};
typedef tagCLEAR_TONG_CLAIMWAR_SYNC CLEAR_TONG_CLAIMWAR_SYNC;

struct tagCURPLAYER_NORMAL_SYNC : tagProtocolHeader {
    short int m_shStamina;
    int m_nMana;
    int m_nLife;
    short int m_shAngry;
    BYTE m_btTeamData;
};
typedef tagCURPLAYER_NORMAL_SYNC CURPLAYER_NORMAL_SYNC;

struct tagCURPLAYER_SYNC : tagProtocolHeader {
    DWORD m_dwID;
    BYTE m_btLevel;
    WORD m_wLifeMax;
    WORD m_wStaminaMax;
    BYTE m_btSex;
    BYTE m_btKind;
    BYTE m_btSeries;
    WORD m_wManaMax;
    int m_HeadImage;
    WORD m_wAttributePoint;
    WORD m_wEngergy;
    WORD m_wLucky;
    WORD m_wSkillPoint;
    WORD m_wStrength;
    WORD m_wDexterity;
    WORD m_wVitality;
    INT64 m_nExp;
    DWORD m_dwLeadExp;
    BYTE m_byBoxParam;
    BYTE m_btCurFaction;
    WORD m_nFactionAddTimes;
    short int m_nExpEx;
    BYTE m_btLastFaction;
    WORD m_wSectStat;
    WORD m_wWorldStat;
    int m_nMoney2;
    int m_nMoney1;
    int m_nRenascenceCount;
};
typedef tagCURPLAYER_SYNC CURPLAYER_SYNC;

struct tagChangeExtPoint : tagProtocolHeader {
    BYTE szAccountName[32];
    union {
        unsigned int uExtPointIndex;
        unsigned int uSilverType;
    };
    int nChangeValue;
    unsigned int uFlag;
    int nPlayerDataIndex;
};

struct tagDayTime : tagProtocolHeader {
    int tm_year;
    int tm_month;
    int tm_mday;
    int tm_hour;
    int tm_min;
    int tm_sec;
};

struct tagDynamicUpdateMapID : tagProtocolHeader {
    int nMapId;
    int nAction;
};

struct tagEnterGame : tagProtocolHeader {
    BYTE szAccountName[32];
};

struct tagFOUNDRY_CLIENTSEND : tagProtocolHeader {
    BYTE eFoundryType;
    int nNecItemNum;
    tagFOUNDRY_CLIENTSEND_NecItemPos_t NecItemPos[8];
    BYTE nSelItemNum;
    tagFOUNDRY_CLIENTSEND_NecItemPos_t SelItemPos[8];
    int nExParam;
    BYTE byResScheme;
};
typedef tagFOUNDRY_CLIENTSEND FOUNDRY_CLIENTSEND;

struct tagFOUNDRY_RESULT : tagProtocolHeader {
    BYTE eFoundryType;
    int nNewItemID;
    BYTE nResult;
};
typedef tagFOUNDRY_RESULT FOUNDRY_RESULT;

struct tagGIVE_SOMETHING : tagProtocolHeader {
    BYTE byGiveType;
    DWORD dwTarID;
    DWORD dwItemID[6];
};
typedef tagGIVE_SOMETHING GIVE_SOMETHING;

struct tagGPI_VIEW_ROLLING_ITEM : tagProtocolHeader {
    SViewItemInfo item;
    WORD wLifeTime;
    DWORD dwDiceID;
};
typedef tagGPI_VIEW_ROLLING_ITEM GPI_VIEW_ROLLING_ITEM;

struct tagGameSvrInfo : tagProtocolHeader {
    UINT nIPAddr_Intraner;
    UINT nIPAddr_Internet;
    short unsigned int nPort;
    WORD wCapability;
};

struct tagGateWayKickOut : tagProtocolHeader {
    int nKickOutFlag;
    BYTE szAccountName[32];
};

struct tagITEM_AUTO_MOVE_SYNC : tagProtocolHeader {
    BYTE m_btSrcY;
    BYTE m_btDestY;
    BYTE m_btSrcPos;
    BYTE m_btSrcX;
    BYTE m_btDestX;
    BYTE m_btDestPos;
};
typedef tagITEM_AUTO_MOVE_SYNC ITEM_AUTO_MOVE_SYNC;

struct tagITEM_COUNT_SYNC : tagProtocolHeader {
    DWORD m_nID;
    int m_nCurCount;
};
typedef tagITEM_COUNT_SYNC ITEM_COUNT_SYNC;

struct tagITEM_DURABILITY_CHANGE : tagProtocolHeader {
    DWORD dwItemID;
    int nCurMaxDur;
    int nCurDur;
};
typedef tagITEM_DURABILITY_CHANGE ITEM_DURABILITY_CHANGE;

struct tagITEM_MASK : tagProtocolHeader {
    char cEquip[15];
};
typedef tagITEM_MASK ITEM_MASK;

struct tagITEM_REMOVE_SYNC : tagProtocolHeader {
    int m_ID;
};
typedef tagITEM_REMOVE_SYNC ITEM_REMOVE_SYNC;

struct tagITEM_REPAIR : tagProtocolHeader {
    DWORD dwItemID;
    DWORD Param;
};
typedef tagITEM_REPAIR ITEM_REPAIR;

struct tagItemSync : tagProtocolHeader, SViewItemInfo {
    WORD m_MaxDurability;
    WORD m_Durability;
    BYTE m_btPlace;
    BYTE m_btY;
    BYTE m_btX;
    DWORD m_nWidth;
    DWORD m_nHeight;
};
typedef tagItemSync ITEM_SYNC;

struct tagLADDER_DATA : tagProtocolHeader {
    DWORD dwLadderID;
    BYTE btRoleCount;
    TRoleList StatData[10];
};
typedef tagLADDER_DATA LADDER_DATA;

struct tagLADDER_LIST : tagProtocolHeader {
    WORD wSize;
    int nCount;
    DWORD dwLadderID[];
};
typedef tagLADDER_LIST LADDER_LIST;

struct tagLADDER_QUERY : tagProtocolHeader {
    WORD wSize;
    BYTE btIDCount;
    DWORD dwLadderID[];
};
typedef tagLADDER_QUERY LADDER_QUERY;

struct tagLeaveGame : tagProtocolHeader {
    BYTE cCmdType;
    int nExtPoint;
    char szAccountName[32];
};

struct tagLogicLogin : tagProtocolHeader {
    GUID guid;
};

struct tagMINIMAP_OBJ_SYNC : tagProtocolHeader {
    WORD wSize;
    MiniMapObjType eType;
    DWORD dwMpsX;
    DWORD dwMpsY;
};

struct tagNOTIFY_CLIENT : tagProtocolHeader {
    INT nNotifyType;
    union {
        INT nStatus;
        CHAR cStatus[4];
    };
};
typedef tagNOTIFY_CLIENT NOTIFY_CLIENT;

struct tagNPC_CHGCAMP_SYNC : tagProtocolHeader {
    DWORD ID;
    BYTE Camp;
};
typedef tagNPC_CHGCAMP_SYNC NPC_CHGCAMP_SYNC;

struct tagNPC_CHGCURCAMP_SYNC : tagProtocolHeader {
    DWORD ID;
    BYTE Camp;
};
typedef tagNPC_CHGCURCAMP_SYNC NPC_CHGCURCAMP_SYNC;

struct tagNPC_DEATH_SYNC : tagProtocolHeader {
    DWORD m_dwID;
};
typedef tagNPC_DEATH_SYNC NPC_DEATH_SYNC;

struct tagNPC_GOLD_CHANGE_SYNC : tagProtocolHeader {
    DWORD m_dwNpcID;
    WORD m_wGoldFlag;
};
typedef tagNPC_GOLD_CHANGE_SYNC NPC_GOLD_CHANGE_SYNC;

struct tagNPC_JUMP_COMMAND : tagProtocolHeader {
    int nMpsX;
    int nMpsY;
    DWORD Reserved;
};
typedef tagNPC_JUMP_COMMAND NPC_JUMP_COMMAND;

struct tagNPC_JUMP_SYNC : tagProtocolHeader {
    int nMpsY;
    int nMpsX;
    DWORD ID;
};
typedef tagNPC_JUMP_SYNC NPC_JUMP_SYNC;

struct tagNPC_NET_COMMAND : tagProtocolHeader {
    DWORD dwNpcID;
    BYTE btCmd;
    int nX;
    int nY;
    int nParam1;
    int nParam2;
};
typedef tagNPC_NET_COMMAND NPC_NET_COMMAND;

struct tagNPC_NORMAL_SYNC : tagProtocolHeader {
    DWORD ID;
    DWORD MapX;
    BYTE Camp;
    BYTE State;
    DWORD MapY;
    BYTE LifePerCent;
    BYTE Doing;
    BYTE bIsSyncName;
};
typedef tagNPC_NORMAL_SYNC NPC_NORMAL_SYNC;

struct tagNPC_PET_SYNC : tagProtocolHeader {
    DWORD ID;
    char szName[256];
};
typedef tagNPC_PET_SYNC NPC_PET_SYNC;

struct tagNPC_PLAYER_TYPE_NORMAL_SYNC : tagProtocolHeader {
    WORD m_wOffY;
    WORD m_wOffX;
    DWORD m_dwMapY;
    DWORD m_dwMapX;
};
typedef tagNPC_PLAYER_TYPE_NORMAL_SYNC NPC_PLAYER_TYPE_NORMAL_SYNC;

struct tagNPC_POS_SYNC : tagProtocolHeader {
    DWORD ID;
    DWORD m_dwMapY;
    DWORD m_dwMapX;
    DWORD m_dwExParam;
};
typedef tagNPC_POS_SYNC NPC_POS_SYNC;

struct tagNPC_RANKID_SYNC : tagProtocolHeader {
    BYTE m_btRankId;
    DWORD m_dwNpcID;
};
typedef tagNPC_RANKID_SYNC NPC_RANKID_SYNC;

struct tagNPC_REMOVE_SYNC : tagProtocolHeader {
    DWORD ID;
};
typedef tagNPC_REMOVE_SYNC NPC_REMOVE_SYNC;

struct tagNPC_REQUEST_COMMAND : tagProtocolHeader {
    DWORD ID;
};
typedef tagNPC_REQUEST_COMMAND NPC_REQUEST_COMMAND;

struct tagNPC_REVIVE_SYNC : tagProtocolHeader {
    DWORD ID;
    BYTE Type;
};
typedef tagNPC_REVIVE_SYNC NPC_REVIVE_SYNC;

struct tagNPC_RUN_SYNC : tagProtocolHeader {
    int nMpsY;
    DWORD ID;
    int nMpsX;
};
typedef tagNPC_RUN_SYNC NPC_RUN_SYNC;

struct tagNPC_SET_MENU_STATE_SYNC : tagProtocolHeader {
    WORD m_wLength;
    DWORD m_dwID;
    BYTE m_btState;
    char m_szSentence[256];
};
typedef tagNPC_SET_MENU_STATE_SYNC NPC_SET_MENU_STATE_SYNC;

struct tagNPC_SIT_COMMAND : tagProtocolHeader {
    BYTE m_btSitFlag;
};
typedef tagNPC_SIT_COMMAND NPC_SIT_COMMAND;

struct tagNPC_SKILL_SYNC : tagProtocolHeader {
    int nMpsX;
    int nSkillID;
    int nMpsY;
    DWORD ID;
    int nSkillLevel;
    int nSyncCD;
};
typedef tagNPC_SKILL_SYNC NPC_SKILL_SYNC;

struct tagNPC_SLEEP_SYNC : tagProtocolHeader {
    BYTE bSleep;
    DWORD NpcID;
};
typedef tagNPC_SLEEP_SYNC NPC_SLEEP_SYNC;

struct tagNPC_SYNC : tagProtocolHeader {
    WORD m_wLength;
    BYTE CurrentCamp;
    BYTE m_bySeries;
    BYTE LifePerCent;
    DWORD MpsY;
    BYTE m_Doing;
    BYTE Camp;
    DWORD MpsX;
    BYTE m_btMenuState;
    WORD NpcEnchant;
    BYTE m_btKind;
    DWORD ID;
    DWORD dwOwnerID;
    int NpcSettingIdx;
    BYTE byRenascenceCount;
    char m_szName[64];
};
typedef tagNPC_SYNC NPC_SYNC;

struct tagNPC_SYNC_STATEINFO : tagProtocolHeader {
    BYTE m_btStateInfo[6];
    DWORD m_ID;
};
typedef tagNPC_SYNC_STATEINFO NPC_SYNC_STATEINFO;

struct tagNPC_WALK_SYNC : tagProtocolHeader {
    DWORD ID;
    int nMpsY;
    int nMpsX;
};
typedef tagNPC_WALK_SYNC NPC_WALK_SYNC;

struct tagNotifyPlayerExchange : tagProtocolHeader {
    BYTE byBusinessVersion;
    BYTE byProtocolVersion;
    GUID sGuid;
    UINT nIPAddr;
    short unsigned int nPort;
};

struct tagOBJ_ADD_SYNC : tagProtocolHeader {
    WORD m_wLength;
    BYTE m_btState;
    int m_nID;
    int m_nDataID;
    int m_nXpos;
    int m_nYpos;
    int m_nItemCount;
    int m_nItemID;
    BYTE m_btDir;
    BYTE m_btItemWidth;
    WORD m_wCurFrame;
    BYTE m_btItemHeight;
    BYTE m_btColorID;
    BYTE m_btFlag;
    char m_szName[32];
};
typedef tagOBJ_ADD_SYNC OBJ_ADD_SYNC;

struct tagOBJ_MOUSE_CLICK_SYNC : tagProtocolHeader {
    int m_dwRegionID;
    int m_nObjID;
};
typedef tagOBJ_MOUSE_CLICK_SYNC OBJ_MOUSE_CLICK_SYNC;

struct tagOBJ_SYNC_DIR : tagProtocolHeader {
    BYTE m_btDir;
    int m_nID;
};
typedef tagOBJ_SYNC_DIR OBJ_SYNC_DIR;

struct tagOBJ_SYNC_REMOVE : tagProtocolHeader {
    int m_nID;
    BYTE m_btSoundFlag;
};
typedef tagOBJ_SYNC_REMOVE OBJ_SYNC_REMOVE;

struct tagOBJ_SYNC_STATE : tagProtocolHeader {
    BYTE m_btState;
    int m_nID;
};
typedef tagOBJ_SYNC_STATE OBJ_SYNC_STATE;

struct tagOBJ_SYNC_TRAP_ACT : tagProtocolHeader {
    int m_nID;
    int m_nTarX;
    int m_nTarY;
};
typedef tagOBJ_SYNC_TRAP_ACT OBJ_SYNC_TRAP_ACT;

struct tagONE_ATTR_SYNC : tagProtocolHeader {
    int nAttrType;
    int nAttrValue;
};
typedef tagONE_ATTR_SYNC ONE_ATTR_SYNC;

struct tagOPEN_STORE_BOX_SYNC : tagProtocolHeader {
    BYTE byGainState;
    BYTE byBoxPasswordParam;
};
typedef tagOPEN_STORE_BOX_SYNC OPEN_STORE_BOX_SYNC;

struct tagOfflineRequestReq : tagProtocolHeader {
    char szAccount[32];
    char szRole[32];
};

struct tagPING_CLIENTREPLY_COMMAND : tagProtocolHeader {
    DWORD m_dwReplyServerTime;
    DWORD m_dwClientTime;
};
typedef tagPING_CLIENTREPLY_COMMAND PING_CLIENTREPLY_COMMAND;

struct tagPING_COMMAND : tagProtocolHeader {
    DWORD m_dwTime;
};
typedef tagPING_COMMAND PING_COMMAND;

struct tagPK_APPLY_ENMITY_COMMAND : tagProtocolHeader {
    DWORD m_dwNpcID;
};
typedef tagPK_APPLY_ENMITY_COMMAND PK_APPLY_ENMITY_COMMAND;

struct tagPK_APPLY_NORMAL_FLAG_COMMAND : tagProtocolHeader {
    BYTE m_btState;
};
typedef tagPK_APPLY_NORMAL_FLAG_COMMAND PK_APPLY_NORMAL_FLAG_COMMAND;

struct tagPK_ENMITY_STATE_SYNC : tagProtocolHeader {
    WORD m_wLength;
    BYTE m_btState;
    DWORD m_dwNpcID;
    char m_szName[32];
};
typedef tagPK_ENMITY_STATE_SYNC PK_ENMITY_STATE_SYNC;

struct tagPK_EXERCISE_STATE_SYNC : tagProtocolHeader {
    WORD m_wLength;
    BYTE m_btState;
    DWORD m_dwNpcID;
    char m_szName[32];
};
typedef tagPK_EXERCISE_STATE_SYNC PK_EXERCISE_STATE_SYNC;

struct tagPK_NORMAL_FLAG_SYNC : tagProtocolHeader {
    BYTE m_btFlag;
};
typedef tagPK_NORMAL_FLAG_SYNC PK_NORMAL_FLAG_SYNC;

struct tagPK_VALUE_SYNC : tagProtocolHeader {
    int m_nPKValue;
};
typedef tagPK_VALUE_SYNC PK_VALUE_SYNC;

struct tagPLAYER_ADD_BASE_ATTRIBUTE_COMMAND : tagProtocolHeader {
    BYTE m_btAttribute;
    int m_nAddNo;
    DWORD Reserved[2];
};
typedef tagPLAYER_ADD_BASE_ATTRIBUTE_COMMAND PLAYER_ADD_BASE_ATTRIBUTE_COMMAND;

struct tagPLAYER_ADD_SKILL_POINT_COMMAND : tagProtocolHeader {
    int m_nSkillID;
    int m_nAddPoint;
    DWORD Reserved[2];
};
typedef tagPLAYER_ADD_SKILL_POINT_COMMAND PLAYER_ADD_SKILL_POINT_COMMAND;

struct tagPLAYER_ALL_TASKVALUE_SYNC : tagProtocolHeader {
    tagPLAYER_ALL_TASKVALUE_SYNC_TaskArray_t TaskArray[80];
};
typedef tagPLAYER_ALL_TASKVALUE_SYNC PLAYER_ALL_TASKVALUE_SYNC;

struct tagPLAYER_ATTRIBUTE_SYNC : tagProtocolHeader {
    BYTE m_btAttribute;
    int m_nBasePoint;
    int m_nCurPoint;
    int m_nLeavePoint;
};
typedef tagPLAYER_ATTRIBUTE_SYNC PLAYER_ATTRIBUTE_SYNC;

struct tagPLAYER_BUY_ITEM_COMMAND : tagProtocolHeader {
    BYTE m_Y;
    BYTE m_X;
    BYTE m_Place;
    int m_BuyIdx;
    DWORD Reserved;
};
typedef tagPLAYER_BUY_ITEM_COMMAND PLAYER_BUY_ITEM_COMMAND;

struct tagPLAYER_DIALOG_NPC_COMMAND : tagProtocolHeader {
    int nNpcId;
    DWORD dwCheckValue;
};
typedef tagPLAYER_DIALOG_NPC_COMMAND PLAYER_DIALOG_NPC_COMMAND;

struct tagPLAYER_DISABLEDFLAG_SYNC : tagProtocolHeader {
    DWORD m_dwFlags;
};
typedef tagPLAYER_DISABLEDFLAG_SYNC PLAYER_DISABLEDFLAG_SYNC;

struct tagPLAYER_DIVIDE_ITEM_COMMAND : tagProtocolHeader {
    DWORD m_nID;
    int m_nDivideCount;
    BYTE m_byContinuouslyDivide;
};
typedef tagPLAYER_DIVIDE_ITEM_COMMAND PLAYER_DIVIDE_ITEM_COMMAND;

struct tagPLAYER_EAT_ITEM_COMMAND : tagProtocolHeader {
    BYTE m_btX;
    int m_nItemID;
    BYTE m_btY;
    BYTE m_btPlace;
    DWORD dwAntiBot;
    DWORD dwTargetID;
};
typedef tagPLAYER_EAT_ITEM_COMMAND PLAYER_EAT_ITEM_COMMAND;

struct tagPLAYER_EXP_SYNC2 : tagProtocolHeader {
    INT64 m_i64Exp;
};
typedef tagPLAYER_EXP_SYNC2 PLAYER_EXP_SYNC2;

struct tagPLAYER_FACTION_DATA : tagProtocolHeader {
    BYTE m_btCamp;
    BYTE m_btCurFaction;
    BYTE m_btLastFaction;
    int m_nAddTimes;
};
typedef tagPLAYER_FACTION_DATA PLAYER_FACTION_DATA;

struct tagPLAYER_FACTION_SKILL_LEVEL : tagProtocolHeader {
    BYTE m_btCurFactionID;
    BYTE m_btLevel;
};
typedef tagPLAYER_FACTION_SKILL_LEVEL PLAYER_FACTION_SKILL_LEVEL;

struct tagPLAYER_GIVEITEMSEND : tagProtocolHeader {
    WORD wSize;
    int nParam1;
    int nItemCount;
    GiveItemPos Part[];
};
typedef tagPLAYER_GIVEITEMSEND PLAYER_GIVEITEMSEND;

struct tagPLAYER_LEAD_EXP_SYNC : tagProtocolHeader {
    DWORD m_dwLeadExp;
};
typedef tagPLAYER_LEAD_EXP_SYNC PLAYER_LEAD_EXP_SYNC;

struct tagPLAYER_LEAVE_FACTION : tagProtocolHeader {
};
typedef tagPLAYER_LEAVE_FACTION PLAYER_LEAVE_FACTION;

struct tagPLAYER_LEVEL_UP_SYNC : tagProtocolHeader, KRESIST_ATTR {
    BYTE m_btLevel;
    INT64 m_nExp;
    int m_nAttributePoint;
    WORD m_nSkillPoint;
    short int m_nExpEx;
    int m_nBaseLifeMax;
    int m_nBaseStaminaMax;
    int m_nBaseManaMax;
};
typedef tagPLAYER_LEVEL_UP_SYNC PLAYER_LEVEL_UP_SYNC;

struct tagPLAYER_MONEY_SYNC : tagProtocolHeader {
    int m_nMoney1;
    int m_nMoney2;
    int m_nMoney3;
};
typedef tagPLAYER_MONEY_SYNC PLAYER_MONEY_SYNC;

struct tagPLAYER_MOVE_ITEM_COMMAND : tagProtocolHeader {
    BYTE m_btDownY;
    BYTE m_btUpX;
    BYTE m_btDownPos;
    BYTE m_btDownX;
    BYTE m_btUpY;
    BYTE m_btUpPos;
};
typedef tagPLAYER_MOVE_ITEM_COMMAND PLAYER_MOVE_ITEM_COMMAND;

struct tagPLAYER_MOVE_ITEM_SYNC : tagProtocolHeader {
    BYTE m_btDownY;
    BYTE m_btDownPos;
    BYTE m_btDownX;
    BYTE m_btUpY;
    BYTE m_btUpX;
    BYTE m_btUpPos;
};
typedef tagPLAYER_MOVE_ITEM_SYNC PLAYER_MOVE_ITEM_SYNC;

struct tagPLAYER_PICKUP_ITEM_COMMAND : tagProtocolHeader {
    BYTE m_btPosY;
    BYTE m_btPosX;
    BYTE m_btPosType;
    int m_nObjID;
    DWORD Reserved;
};
typedef tagPLAYER_PICKUP_ITEM_COMMAND PLAYER_PICKUP_ITEM_COMMAND;

struct tagPLAYER_SCRIPTACTION_SYNC : tagProtocolHeader {
    WORD m_wProtocolLong;
    BYTE m_nOperateType;
    BYTE m_bUIId;
    BYTE m_bOptionNum;
    BYTE m_bParam1;
    BYTE m_bParam2;
    int m_nParam;
    int m_nBufferLen;
    char m_pContent[900];
};
typedef tagPLAYER_SCRIPTACTION_SYNC PLAYER_SCRIPTACTION_SYNC;

struct tagPLAYER_SELL_ITEM_COMMAND : tagProtocolHeader {
    int m_ID;
    DWORD Reserved[2];
};
typedef tagPLAYER_SELL_ITEM_COMMAND PLAYER_SELL_ITEM_COMMAND;

struct tagPLAYER_SET_PK : tagProtocolHeader {
    BYTE m_btPKFlag;
};
typedef tagPLAYER_SET_PK PLAYER_SET_PK;

struct tagPLAYER_SKILL_LEVEL_SYNC : tagProtocolHeader {
    int m_nSkillID;
    int m_nSkillLevel;
    int m_nLeavePoint;
    short int m_wSkillExpPercent;
};
typedef tagPLAYER_SKILL_LEVEL_SYNC PLAYER_SKILL_LEVEL_SYNC;

struct tagPLAYER_SYNC : tagProtocolHeader {
    WORD m_wLength;
    BYTE WalkSpeed;
    BYTE AttackSpeed;
    BYTE RunSpeed;
    BYTE ArmorType;
    BYTE HelmType;
    BYTE RankID;
    DWORD ID;
    BYTE HorseType;
    BYTE m_btSomeFlag;
    BYTE CastSpeed;
    BYTE WeaponType;
    BYTE m_btSex;
    WORD m_wTitleID;
    DWORD m_dwTongNameID;
    char m_szTongCall[64];
};
typedef tagPLAYER_SYNC PLAYER_SYNC;

struct tagPLAYER_TASKVALUE_SYNC : tagProtocolHeader {
    int nTaskID;
    int nTaskValue;
};
typedef tagPLAYER_TASKVALUE_SYNC PLAYER_TASKVALUE_SYNC;

struct tagPLAYER_THROW_AWAY_ITEM_COMMAND : tagProtocolHeader {
};
typedef tagPLAYER_THROW_AWAY_ITEM_COMMAND PLAYER_THROW_AWAY_ITEM_COMMAND;

struct tagPermitPlayerExchange : tagProtocolHeader {
    char szAccount[32];
    GUID guid;
    DWORD dwIp;
    WORD wPort;
    bool bPermit;
};

struct tagProtoHeader : tagProtocolHeader {
};

struct tagProtocolHeader2 : tagProtocolHeader {
    long unsigned int ulIdentity;
};

struct tagProtocolLengthHeader : tagProtocolHeader {
    WORD m_wProcotolSize;
};

struct tagQueryMapInfo : tagProtocolHeader {
    unsigned int uTime;
    int nClientID;
    TTm timeTm;
};

struct tagRegisterAccount : tagProtocolHeader {
    BYTE szAccountName[32];
};

struct tagRelaySDBOper : tagRelaySDBRecord {
    BYTE byData[1];
};

struct tagReturnChangeExtPoint : tagProtocolHeader {
    int nResult;
    BYTE szAccountName[32];
    unsigned int uFlag;
    int nPlayerDataIndex;
};

struct tagRoleEnterGame : tagProtocolHeader {
    bool bLock;
    char Name[32];
};

struct tagSALE_BOX_SYNC : tagProtocolHeader {
    int nShopIndex;
    int nScale;
    int nCurrencyType;
};
typedef tagSALE_BOX_SYNC SALE_BOX_SYNC;

struct tagSALE_STORES_CHANGE_SHOP : tagProtocolHeader {
    int m_nNewShopIndex;
};
typedef tagSALE_STORES_CHANGE_SHOP SALE_STORES_CHANGE_SHOP;

struct tagSALE_STORES_SYNC : tagProtocolHeader {
    SALE_STORES_SHOP sStoresShopInfo[12];
};
typedef tagSALE_STORES_SYNC SALE_STORES_SYNC;

struct tagSHOW_MSG_SYNC : tagProtocolHeader {
    WORD m_wLength;
    WORD m_wMsgID;
    LPVOID m_lpBuf;
};
typedef tagSHOW_MSG_SYNC SHOW_MSG_SYNC;

struct tagSKILL_CHANGEAURASKILL_COMMAND : tagProtocolHeader {
    int m_nAuraSkill;
};
typedef tagSKILL_CHANGEAURASKILL_COMMAND SKILL_CHANGEAURASKILL_COMMAND;

struct tagSKILL_SEND_ALL_SYNC : tagProtocolHeader {
    WORD m_wProtocolLong;
    tagSKILL_SEND_ALL_SYNC_m_sAllSkill_t m_sAllSkill[80];
};
typedef tagSKILL_SEND_ALL_SYNC SKILL_SEND_ALL_SYNC;

struct tagSTATE_EFFECT_SYNC : tagProtocolHeader {
    WORD m_wLength;
    DWORD m_dwNpcID;
    DWORD m_dwSkillID;
    int m_nLevel;
    int m_nTime;
    BYTE m_bNoClearOnDeath;
    KMagicAttrib m_MagicAttrib[20];
};
typedef tagSTATE_EFFECT_SYNC STATE_EFFECT_SYNC;

struct tagSTORE_MONEY_COMMAND : tagProtocolHeader {
    BYTE m_byDir;
    DWORD m_dwMoney;
    DWORD Reserved[2];
};
typedef tagSTORE_MONEY_COMMAND STORE_MONEY_COMMAND;

struct tagSYNC_WEATHER : tagProtocolHeader {
    BYTE WeatherID;
};
typedef tagSYNC_WEATHER SYNC_WEATHER;

struct tagSearchWay : tagProtocolHeader {
    int lnID;
    int nIndex;
    DWORD dwPlayerID;
};

struct tagSyncBotSignCode : tagProtocolHeader {
    WORD wLength;
    int nCount;
    BYTE pBuffer[1];
};

struct tagTEXTCMD : tagProtocolHeader {
    WORD m_wLength;
    char m_TextCmd[1];
};
typedef tagTEXTCMD TEXTCMD;

struct tagTHROW_AWAY_ALL_MEDICINE_COMMAND : tagProtocolHeader {
    BYTE byRoom;
    BYTE byDetailType;
    BYTE byParam;
};
typedef tagTHROW_AWAY_ALL_MEDICINE_COMMAND THROW_AWAY_ALL_MEDICINE_COMMAND;

struct tagTONG_ACCEPT_MEMBER_COMMAND : tagProtocolHeader {
    WORD m_wLength;
    BYTE m_btMsgId;
    int m_nPlayerIdx;
    DWORD m_dwNameID;
    BYTE m_btFlag;
};
typedef tagTONG_ACCEPT_MEMBER_COMMAND TONG_ACCEPT_MEMBER_COMMAND;

struct tagTONG_APPLY_ADD_COMMAND : tagProtocolHeader {
    WORD m_wLength;
    BYTE m_btMsgId;
    DWORD m_dwNpcID;
};
typedef tagTONG_APPLY_ADD_COMMAND TONG_APPLY_ADD_COMMAND;

struct tagTONG_APPLY_ADD_SYNC : tagProtocolHeader {
    WORD m_wLength;
    BYTE m_btMsgId;
    int m_nPlayerIdx;
    char m_szName[32];
};
typedef tagTONG_APPLY_ADD_SYNC TONG_APPLY_ADD_SYNC;

struct tagTONG_APPLY_ADD_UNION_COMMAND : tagProtocolHeader {
    WORD m_wLength;
    BYTE m_btMsgId;
    DWORD m_dwNpcID;
};
typedef tagTONG_APPLY_ADD_UNION_COMMAND TONG_APPLY_ADD_UNION_COMMAND;

struct tagTONG_APPLY_CHANGE_JOB_CALL_COMMAND : tagProtocolHeader {
    WORD m_wLength;
    BYTE m_btMsgId;
    BYTE m_btFigure;
    DWORD m_dwMemberID;
    DWORD m_dwTongNameID;
    DWORD m_dwExecutorMemberID;
    char m_szCall[32];
};
typedef tagTONG_APPLY_CHANGE_JOB_CALL_COMMAND TONG_APPLY_CHANGE_JOB_CALL_COMMAND;

struct tagTONG_APPLY_CHANGE_MASTER_COMMAND : tagProtocolHeader {
    WORD m_wLength;
    BYTE m_btMsgId;
    DWORD m_dwTongNameID;
    BYTE m_btFigure;
    BYTE m_btPos;
    char m_szName[32];
};
typedef tagTONG_APPLY_CHANGE_MASTER_COMMAND TONG_APPLY_CHANGE_MASTER_COMMAND;

struct tagTONG_APPLY_CREATE_COMMAND : tagProtocolHeader {
    WORD m_wLength;
    BYTE m_btMsgId;
    BYTE m_btCamp;
    char m_szName[9];
};
typedef tagTONG_APPLY_CREATE_COMMAND TONG_APPLY_CREATE_COMMAND;

struct tagTONG_APPLY_INSTATE_COMMAND : tagProtocolHeader {
    WORD m_wLength;
    BYTE m_btMsgId;
    DWORD m_dwTongNameID;
    BYTE m_btCurFigure;
    BYTE m_btNewFigure;
    char m_szName[32];
};
typedef tagTONG_APPLY_INSTATE_COMMAND TONG_APPLY_INSTATE_COMMAND;

struct tagTONG_APPLY_LEAVE_COMMAND : tagProtocolHeader {
    WORD m_wLength;
    BYTE m_btMsgId;
    DWORD m_dwTongNameID;
    BYTE m_btFigure;
    BYTE m_btPos;
    char m_szName[32];
};
typedef tagTONG_APPLY_LEAVE_COMMAND TONG_APPLY_LEAVE_COMMAND;

struct tagTONG_APPLY_UNION_INFO_COMMAND : tagProtocolHeader {
    WORD m_wLength;
    BYTE m_btMsgId;
    DWORD m_dwNpcID;
    DWORD m_dwTongNameID;
};
typedef tagTONG_APPLY_UNION_INFO_COMMAND TONG_APPLY_UNION_INFO_COMMAND;

struct tagTONG_Add_SYNC : tagProtocolHeader {
    WORD m_wLength;
    BYTE m_btMsgId;
    BYTE m_btCamp;
    DWORD m_dwMemberID;
    DWORD m_dwJoinTime;
    char m_szTongName[32];
    char m_szTitle[32];
    char m_szMaster[32];
};
typedef tagTONG_Add_SYNC TONG_Add_SYNC;

struct tagTONG_BILLBOARD_COMMAND : tagProtocolHeader {
    WORD m_wLength;
    BYTE m_btMsgId;
};
typedef tagTONG_BILLBOARD_COMMAND TONG_BILLBOARD_COMMAND;

struct tagTONG_BILLBOARD_SYNC : tagProtocolHeader {
    WORD m_wLength;
    BYTE m_btMsgId;
    DWORD m_dwMemberNum[10];
    BYTE m_btDataNum;
    BYTE m_btCamp[10];
    BYTE m_btNameLen[10];
    char m_szName[320];
};
typedef tagTONG_BILLBOARD_SYNC TONG_BILLBOARD_SYNC;

struct tagTONG_CHANGE_JOB_CALL_SYNC : tagProtocolHeader {
    WORD m_wLength;
    BYTE m_btMsgId;
    DWORD m_dwTongNameID;
    BYTE m_btFigure;
    DWORD m_dwMemberID;
    char m_szCall[32];
};
typedef tagTONG_CHANGE_JOB_CALL_SYNC TONG_CHANGE_JOB_CALL_SYNC;

struct tagTONG_CHANGE_MASTER_FAIL_SYNC : tagProtocolHeader {
    WORD m_wLength;
    BYTE m_btMsgId;
    DWORD m_dwTongNameID;
    BYTE m_btFailID;
    char m_szName[32];
};
typedef tagTONG_CHANGE_MASTER_FAIL_SYNC TONG_CHANGE_MASTER_FAIL_SYNC;

struct tagTONG_CHANGE_MONEY_COMMAND : tagProtocolHeader {
    WORD m_wLength;
    BYTE m_btMsgId;
    DWORD m_dwMoneyFundChange;
    BYTE m_btSaveFlag;
};
typedef tagTONG_CHANGE_MONEY_COMMAND TONG_CHANGE_MONEY_COMMAND;

struct tagTONG_CHANGE_MONEY_RESULT_SYNC : tagProtocolHeader {
    WORD m_wLength;
    BYTE m_btMsgId;
    BYTE m_btSaveFlag;
    BYTE m_btSuccessFlag;
    DWORD m_dwTongNameID;
    DWORD m_dwMoneyFundChange;
    INT64 m_llMoneyFund;
    char m_szName[32];
};
typedef tagTONG_CHANGE_MONEY_RESULT_SYNC TONG_CHANGE_MONEY_RESULT_SYNC;

struct tagTONG_CLAIMWAR_SYNC : tagProtocolHeader {
    WORD m_wLength;
    BYTE m_btMsgId;
    DWORD m_dwEnemy;
};
typedef tagTONG_CLAIMWAR_SYNC TONG_CLAIMWAR_SYNC;

struct tagTONG_CONVENE_COMMAND : tagProtocolHeader {
    WORD m_wLength;
    BYTE m_btMsgId;
    DWORD m_dwDirectorMoney;
    DWORD m_dwManagerMoney;
    DWORD m_dwMemberMoney;
};
typedef tagTONG_CONVENE_COMMAND TONG_CONVENE_COMMAND;

struct tagTONG_CREATE_FAIL_SYNC : tagProtocolHeader {
    WORD m_wLength;
    BYTE m_btMsgId;
    BYTE m_btFailId;
};
typedef tagTONG_CREATE_FAIL_SYNC TONG_CREATE_FAIL_SYNC;

struct tagTONG_CREATE_SYNC : tagProtocolHeader {
    BYTE m_btCamp;
    DWORD m_dwJoinTime;
    DWORD m_dwMemberID;
    char m_szTitle[32];
    char m_szName[9];
};
typedef tagTONG_CREATE_SYNC TONG_CREATE_SYNC;

struct tagTONG_CREATE_UNION_COMMAND : tagProtocolHeader {
    WORD m_wLength;
    BYTE m_btMsgId;
    DWORD m_dwTongNameID;
    char m_szUnionName[32];
};
typedef tagTONG_CREATE_UNION_COMMAND TONG_CREATE_UNION_COMMAND;

struct tagTONG_DISPENSE_COMMAND : tagProtocolHeader {
    WORD m_wLength;
    BYTE m_btMsgId;
    DWORD m_dwDirectorMoney;
    DWORD m_dwManagerMoney;
    DWORD m_dwMemberMoney;
    BYTE m_btIsAll;
};
typedef tagTONG_DISPENSE_COMMAND TONG_DISPENSE_COMMAND;

struct tagTONG_DISPENSE_ERROR_SYNC : tagProtocolHeader {
    WORD m_wLength;
    BYTE m_btMsgId;
    DWORD m_dwTongNameID;
    DWORD m_dwDirectorMoney;
    DWORD m_dwManagerMoney;
    DWORD m_dwMemberMoney;
    BYTE m_btErrorID;
    INT64 m_llMoneyFund;
};
typedef tagTONG_DISPENSE_ERROR_SYNC TONG_DISPENSE_ERROR_SYNC;

struct tagTONG_INSTATE_SYNC : tagProtocolHeader {
    WORD m_wLength;
    BYTE m_btMsgId;
    DWORD m_dwTongNameID;
    BYTE m_btSuccessFlag;
    BYTE m_btSomeFlag;
    BYTE m_btOldFigure;
    BYTE m_btNewFigure;
    char m_szTitle[32];
    char m_szName[32];
};
typedef tagTONG_INSTATE_SYNC TONG_INSTATE_SYNC;

struct tagTONG_KICK_SYNC : tagProtocolHeader {
    WORD m_wLength;
    BYTE m_btMsgId;
    DWORD m_dwTongNameID;
    BYTE m_btSuccessFlag;
    BYTE m_btFigure;
    BYTE m_btPos;
    char m_szName[32];
};
typedef tagTONG_KICK_SYNC TONG_KICK_SYNC;

struct tagTONG_LEAVE_UNION_COMMAND : tagProtocolHeader {
    WORD m_wLength;
    BYTE m_btMsgId;
    BYTE m_btOpeID;
    char m_szName[32];
};
typedef tagTONG_LEAVE_UNION_COMMAND TONG_LEAVE_UNION_COMMAND;

struct tagTONG_LEVEL_BILLBOARD_COMMAND : tagProtocolHeader {
    WORD m_wLength;
    BYTE m_btMsgId;
};
typedef tagTONG_LEVEL_BILLBOARD_COMMAND TONG_LEVEL_BILLBOARD_COMMAND;

struct tagTONG_LEVEL_BILLBOARD_SYNC : tagProtocolHeader {
    WORD m_wLength;
    BYTE m_btMsgId;
    DWORD m_dwExp[10];
    int m_nLevel[10];
    BYTE m_btDataNum;
    BYTE m_btCamp[10];
    BYTE m_btNameLen[10];
    char m_szName[320];
};
typedef tagTONG_LEVEL_BILLBOARD_SYNC TONG_LEVEL_BILLBOARD_SYNC;

struct tagTONG_NPC_CALL_SYNC : tagProtocolHeader {
    WORD m_wLength;
    BYTE m_btMsgId;
    DWORD m_dwNpcID;
    char m_szCall[64];
};
typedef tagTONG_NPC_CALL_SYNC TONG_NPC_CALL_SYNC;

struct tagTONG_REFUSE_ADD_UNION_SYNC : tagProtocolHeader {
    WORD m_wLength;
    BYTE m_btMsgId;
    char m_szName[32];
};
typedef tagTONG_REFUSE_ADD_UNION_SYNC TONG_REFUSE_ADD_UNION_SYNC;

struct tagTONG_REPLY_ADD_UNION_COMMAND : tagProtocolHeader {
    WORD m_wLength;
    BYTE m_btMsgId;
    DWORD dwTongID;
    DWORD dwMemberID;
    BYTE m_btDecision;
};
typedef tagTONG_REPLY_ADD_UNION_COMMAND TONG_REPLY_ADD_UNION_COMMAND;

struct tagTONG_SELF_INFO_SYNC : tagProtocolHeader {
    WORD m_wLength;
    BYTE m_btMsgId;
    BYTE m_btJoinFlag;
    DWORD m_dwMemberID;
    BYTE m_btFigure;
    BYTE m_btCamp;
    BYTE m_btChangeCurCampFlag;
    BYTE m_btUnionFlag;
    BYTE m_btWarState;
    BYTE byIsNationalTitle;
    DWORD m_dwJoinTime;
    char m_szTongName[32];
    char m_szTitle[32];
    char m_szMaster[32];
};
typedef tagTONG_SELF_INFO_SYNC TONG_SELF_INFO_SYNC;

struct tagTONG_TRANSMIT_APPLY_ADD_UNION_SYNC : tagProtocolHeader {
    WORD m_wLength;
    BYTE m_btMsgId;
    DWORD dwTongID;
    DWORD dwMemberID;
    char m_szName[32];
    char m_szTongName[32];
};
typedef tagTONG_TRANSMIT_APPLY_ADD_UNION_SYNC TONG_TRANSMIT_APPLY_ADD_UNION_SYNC;

struct tagTONG_UNION_INFO_SYNC : tagProtocolHeader {
    WORD m_wLength;
    BYTE m_btMsgId;
    DWORD m_dwNpcID;
    BYTE m_btGetType;
    BYTE m_btFlag;
    BYTE m_btUnionFlag;
    BYTE m_btUnionLeader;
    BYTE m_btSelfCamp;
    BYTE m_btUnionCamp;
    BYTE m_btUnionNum;
    DWORD m_dwTongNameID;
    char m_szUnionName[32];
    BYTE m_btNameLength[10];
    char m_szUnionTongName[320];
};
typedef tagTONG_UNION_INFO_SYNC TONG_UNION_INFO_SYNC;

struct tagTRADE_APPLY_OPEN_COMMAND : tagProtocolHeader {
    WORD m_wLength;
    char m_szSentence[256];
};
typedef tagTRADE_APPLY_OPEN_COMMAND TRADE_APPLY_OPEN_COMMAND;

struct tagTRADE_APPLY_START_SYNC : tagProtocolHeader {
    int m_nDestIdx;
    DWORD m_dwNpcId;
};
typedef tagTRADE_APPLY_START_SYNC TRADE_APPLY_START_SYNC;

struct tagTRADE_CHANGE_STATE_SYNC : tagProtocolHeader {
    BYTE m_btState;
    DWORD m_dwNpcID;
};
typedef tagTRADE_CHANGE_STATE_SYNC TRADE_CHANGE_STATE_SYNC;

struct tagTRADE_DECISION_COMMAND : tagProtocolHeader {
    BYTE m_btDecision;
};
typedef tagTRADE_DECISION_COMMAND TRADE_DECISION_COMMAND;

struct tagTRADE_DECISION_SYNC : tagProtocolHeader {
    BYTE m_btDecision;
};
typedef tagTRADE_DECISION_SYNC TRADE_DECISION_SYNC;

struct tagTRADE_MONEY_SYNC : tagProtocolHeader {
    int m_nMoney;
};
typedef tagTRADE_MONEY_SYNC TRADE_MONEY_SYNC;

struct tagTRADE_MOVE_MONEY_COMMAND : tagProtocolHeader {
    int m_nMoney;
};
typedef tagTRADE_MOVE_MONEY_COMMAND TRADE_MOVE_MONEY_COMMAND;

struct tagTRADE_STATE_SYNC : tagProtocolHeader {
    BYTE m_btSelfLock;
    BYTE m_btDestLock;
    BYTE m_btSelfOk;
    BYTE m_btDestOk;
};
typedef tagTRADE_STATE_SYNC TRADE_STATE_SYNC;

struct tagUpdateMapID : tagProtocolHeader {
    bool bRelay;
    int nMapCount;
    int snMapID[];
};

struct tagVIEW_EQUIP_COMMAND : tagProtocolHeader {
    DWORD m_dwNpcID;
};
typedef tagVIEW_EQUIP_COMMAND VIEW_EQUIP_COMMAND;

struct tagVIEW_EQUIP_SYNC : tagProtocolHeader {
    DWORD m_dwNpcID;
    BYTE m_nPKValue;
    short int m_nPortrait;
    short int m_nWorldRank;
    SViewItemInfo m_sInfo[15];
    char m_szMateName[32];
    int m_byRenascenceCount;
    VIEW_OTHER_DETAIL_INFO sDetail;
};
typedef tagVIEW_EQUIP_SYNC VIEW_EQUIP_SYNC;

struct tagWORLD_SYNC : tagProtocolHeader {
    int SubWorld;
    int nMapCopyID;
    int Region;
    BYTE Weather;
    DWORD Frame;
    char szName[16];
};
typedef tagWORLD_SYNC WORLD_SYNC;

struct tag_STEAM_PROTOCOL_HEAD : tagProtocolHeader {
    WORD wLength;
    BYTE btMsgID;
};

struct AUCTION_QUERYLADDERRESULT_S2C : AUCTION_PROTOCOLHEADER {
    WORD wLadderItemCount;
    AuctionLadderItemInfo items[];
};

struct C2S_ACCEPT_TEAM_MEMBER : tag_STEAM_PROTOCOL_HEAD {
    DWORD dwNpcID;
};

struct C2S_APPLY_ADD_TEAM : tag_STEAM_PROTOCOL_HEAD {
    DWORD dwTarNpcID;
};

struct C2S_APPLY_CREATE_TEAM : tag_STEAM_PROTOCOL_HEAD {
    DWORD dwParam;
};

struct C2S_APPLY_LEAVE_TEAM : tag_STEAM_PROTOCOL_HEAD {
    DWORD dwParam;
};

struct C2S_APPLY_TEAM_INFO : tag_STEAM_PROTOCOL_HEAD {
    DWORD dwTarNpcID;
};

struct C2S_APPLY_TEAM_OPEN_CLOSE : tag_STEAM_PROTOCOL_HEAD {
    DWORD dwOpenClose;
};

struct C2S_TEAM_CHANGE_CAPTAIN : tag_STEAM_PROTOCOL_HEAD {
    DWORD dwNpcID;
};

struct C2S_TEAM_DISMISS : tag_STEAM_PROTOCOL_HEAD {
    DWORD dwParam;
};

struct C2S_TEAM_INVITE_ADD : tag_STEAM_PROTOCOL_HEAD {
    DWORD dwNpcID;
};

struct C2S_TEAM_KICK_MEMBER : tag_STEAM_PROTOCOL_HEAD {
    DWORD dwNpcID;
};

struct C2S_TEAM_REPLY_INVITE : tag_STEAM_PROTOCOL_HEAD {
    BYTE btResult;
    int nIndex;
};

struct CHATROOM_C2S_GETMEMBERLIST : CHATROOM_C2S_HEAD {
    char szRoomName[32];
};

struct CHATROOM_C2S_MEMBER : CHATROOM_C2S_HEAD {
    char szRoomName[32];
    char szMember[32];
};

struct CHATROOM_C2S_PASSWORD : CHATROOM_C2S_HEAD {
    char szRoomName[32];
    char szPassword[16];
};

struct CHATROOM_C2S_ROOM : CHATROOM_C2S_HEAD {
    char szRoomName[32];
};

struct CHATROOM_C2S_TALK : CHATROOM_C2S_HEAD {
    char szRoomName[32];
    WORD nMsgLen;
};

struct CHATROOM_R2S_MEMBER : CHATROOM_HEAD {
    char szRoomName[32];
    char szMember[32];
    BYTE nResult;
};

struct CHATROOM_R2S_SYNCBLACKLIST : CHATROOM_HEAD {
    char szRoomName[32];
    char szBlackList[32];
};

struct CHATROOM_RBC_CREATEROOM : CHATROOM_HEAD {
    char szRoomName[32];
    char szAdmin[32];
    char szPassword[16];
    int nLifeTime;
    BYTE nType;
};

struct CHATROOM_RBC_DESTROYROOM : CHATROOM_HEAD {
    char szRoomName[32];
};

struct CHATROOM_RBC_ENTERROOM : CHATROOM_HEAD {
    char szRoomName[32];
    char szMember[32];
    BYTE nSex;
    int nLevel;
};

struct CHATROOM_RBC_MEMBER : CHATROOM_HEAD {
    char szRoomName[32];
    char szMember[32];
};

struct CHATROOM_RBC_PASSWORD : CHATROOM_HEAD {
    char szRoomName[32];
    char szPassword[16];
};

struct CHATROOM_RBC_ROOMTIME : CHATROOM_HEAD {
    char szRoomName[32];
    int nLifeTime;
};

struct CHATROOM_RBC_TALK : CHATROOM_HEAD {
    WORD nMsgLen;
    char szRoomName[32];
    char szMember[32];
};

struct CHATROOM_S2C_KICKEDOUT : CHATROOM_S2C_HEAD {
    char szRoomName[32];
};

struct CHATROOM_S2C_MEMBERLIST : CHATROOM_S2C_HEAD {
    char szRoomName[32];
    BYTE nResult;
    unsigned int nIdentity;
    WORD nCount;
};

struct CHATROOM_S2C_ROOM : CHATROOM_S2C_HEAD {
    char szRoomName[32];
    BYTE nResult;
};

struct CHATROOM_S2C_ROOMLIST : CHATROOM_S2C_HEAD {
    unsigned int nIdentity;
    WORD nCount;
};

struct CHATROOM_S2R_CLOSEROOM : CHATROOM_HEAD {
    char szRoomName[32];
};

struct CHATROOM_S2R_CREATE : CHATROOM_HEAD {
    char szRoomName[32];
    char szPassword[16];
    char szOperator[32];
    int nLifeTime;
};

struct CHATROOM_S2R_ENTERROOM : CHATROOM_HEAD {
    char szRoomName[32];
    char szPassword[16];
    char szMember[32];
    BYTE nSex;
    int nLevel;
};

struct CHATROOM_S2R_M2M : CHATROOM_HEAD {
    char szRoomName[32];
    char szMember[32];
    char szOperator[32];
};

struct CHATROOM_S2R_MEMBER : CHATROOM_HEAD {
    char szRoomName[32];
    char szMember[32];
};

struct CHATROOM_S2R_PASSWORD : CHATROOM_HEAD {
    char szRoomName[32];
    char szPassword[16];
    char szOperator[32];
};

struct CHATROOM_S2R_ROOMTIME : CHATROOM_HEAD {
    char szRoomName[32];
    char szMember[32];
    int nLifeTime;
};

struct CHATROOM_S2R_TALK : CHATROOM_HEAD {
    WORD nMsgLen;
    char szRoomName[32];
    char szMember[32];
};

struct CHATROOM_SBC_CLOSEROOM : CHATROOM_S2C_HEAD {
    char szRoomName[32];
};

struct CHATROOM_SBC_ENTERROOM : CHATROOM_S2C_HEAD {
    char szRoomName[32];
    char szMember[32];
    BYTE nSex;
    int nLevel;
};

struct CHATROOM_SBC_LIFETIMECHANGE : CHATROOM_S2C_HEAD {
    char szRoomName[32];
    int nLifeTime;
};

struct CHATROOM_SBC_MEMBER : CHATROOM_S2C_HEAD {
    char szRoomName[32];
    char szMember[32];
};

struct CHAT_CHANNELCHAT_CMD : tagCHAT_CHANNELCHAT_HEAD {
    WORD wSize;
    DWORD packageID;
    BYTE filter;
    DWORD channelid;
    BYTE cost;
    BYTE sentlen;
    BYTE channelType;
};

struct CHAT_DYNCHANNEL_HEAD : tagCHAT_CHANNELCHAT_HEAD {
    BYTE nMessageType;
};

struct KPROTO_SCRIPTPROTOCOL : tagProtocolLengthHeader {
    WORD wProtocol;
    WORD wDataSize;
};

struct S2C_TEAM_ADD_MEMBER : tag_STEAM_PROTOCOL_HEAD {
    BYTE btLevel;
    DWORD dwNpcID;
    char szName[32];
};

struct S2C_TEAM_APPLY_ADD : tag_STEAM_PROTOCOL_HEAD {
    DWORD dwTarNpcID;
};

struct S2C_TEAM_APPLY_INFO_FALSE : tag_STEAM_PROTOCOL_HEAD {
    BYTE btParam;
};

struct S2C_TEAM_AUTO_CHANGE_CAPTAIN : tag_STEAM_PROTOCOL_HEAD {
    DWORD dwCaptainID;
    DWORD dwMemberID;
};

struct S2C_TEAM_CHANGE_CAPTAIN : tag_STEAM_PROTOCOL_HEAD {
    DWORD dwCaptainID;
    DWORD dwMemberID;
};

struct S2C_TEAM_CREATE_TEAM_FALSE : tag_STEAM_PROTOCOL_HEAD {
    BYTE btErrorID;
};

struct S2C_TEAM_CREATE_TEAM_SUCCESS : tag_STEAM_PROTOCOL_HEAD {
    DWORD dwTeamServerID;
    BYTE byTeamCamp;
};

struct S2C_TEAM_INFO : tag_STEAM_PROTOCOL_HEAD {
    int nCaptain;
    int nMember[7];
    DWORD dwTeamServerID;
};

struct S2C_TEAM_INVITE_ADD : tag_STEAM_PROTOCOL_HEAD {
    int nIdx;
    char szName[32];
};

struct S2C_TEAM_LEAVE : tag_STEAM_PROTOCOL_HEAD {
    DWORD dwNpcID;
};

struct S2C_TEAM_OPEN_CLOSE : tag_STEAM_PROTOCOL_HEAD {
    BYTE btOpenClose;
};

struct S2C_TEAM_SELF_INFO : tag_STEAM_PROTOCOL_HEAD {
    BYTE btState;
    DWORD dwNpcID[8];
    char szNpcName[8][32];
    DWORD dwTeamServerID;
    DWORD dwLeadExp;
    BYTE btLevel[8];
};

struct S2C_TEAM_TEAMMATE_LEVEL : tag_STEAM_PROTOCOL_HEAD {
    BYTE btLevel;
    DWORD dwTeammateID;
};

struct TLockAccount : TUnlockAccount {
    DWORD dwTimeout;
};

struct TRoleNameChangeResult : TRoleNameChange {
    BYTE nResult;
};

struct TRoleNameQueryResult : TRoleNameQuery {
    BYTE nResult;
};

struct TongPort_TongAnnouncement : TongExProtocolGC {
    DWORD dwTongID;
    char szAnnouncement[1024];
};

struct TongPort_TongRecordListInfo : TongExProtocolGC {
    TONG_RECORDLIST_INFO sData;
};

struct TongPort_TongWeekGoalInfo : TongExProtocolGC {
    TONG_WEEKGOAL_INFO sData;
};

struct TongProt_FigureCount : TongExProtocolGC {
    TONG_FIGURE_COUNT sData;
};

struct TongProt_FigureMember : TongExProtocolGC {
    TONG_FIGURE_MEMBER sData;
};

struct TongProt_MemberBase : TongExProtocolGC {
    TONG_MEMBER_BASE sData;
};

struct TongProt_MemberInfo : TongExProtocolGC {
    TONG_MEMBER_INFO sData;
};

struct TongProt_MemberPageData : TongExProtocolGC {
    KTongMemberPageData sData;
};

struct TongProt_MemberRight : TongExProtocolGC {
    BYTE sData[1];
};

struct TongProt_MemberTask : TongExProtocolGC {
    TONG_MEMBER_TASK sData;
};

struct TongProt_SelfMemberMixData : TongExProtocolGC {
    MEMBER_SELF_MIX_DATA sData;
};

struct TongProt_TongBase : TongExProtocolGC {
    TONG_BASE sData;
};

struct TongProt_TongInfo : TongExProtocolGC {
    KTongInfoEx sData;
};

struct TongProt_TongOneData : TongExProtocolGC {
    TONG_TASK sData;
};

struct TongProt_TongPageData : TongExProtocolGC {
    KTongListPageData sData;
};

struct TongProt_UnionBase : TongExProtocolGC {
    TONG_UNION_BASE sData;
};

struct TongProt_UnionPageData : TongExProtocolGC {
    KTongUnionPageData sData;
};

struct TongProt_UnionTongList : TongExProtocolGC {
    KUnionTongList sData;
};

struct TongProt_WorkshopInfo : TongExProtocolGC {
    TONG_WORKSHOP_INFO sData;
};

struct tagAllCitySummary : tagProtocolLengthHeader {
    BYTE byCount;
};
typedef tagAllCitySummary CITY_OWNER_QUERY;

struct tagGatewayBroadCast : tagProtocolHeader2 {
    UINT uCmdType;
    char szData[260];
};

struct tagGuidableInfo : tagProtocolHeader2 {
    GUID guid;
    KACCOUNT_INFO2 sAccountInfo;
    size_t datalength;
    char szData[];
};

struct tagKIB_BuyItemProtocol : tagProtoHeader {
    tagKIB_ItemBuyInfo info;
};

struct tagKIB_BuyItemResultProtocol : tagProtoHeader {
    tagKIB_ItemBuyResult result;
};

struct tagKIB_UseItemProtocol : tagProtoHeader {
    tagKIB_ItemUseInfo info;
};

struct tagKIB_UseItemResultProtocol : tagProtoHeader {
    tagKIB_ItemUseResult result;
};

struct tagOfflineKickoutAsk : tagProtocolHeader2 {
    char szAccount[32];
    int nIndex;
};

struct tagOfflineKickoutRes : tagProtocolHeader2 {
    char szAccount[32];
    BYTE nResult;
    int nExtPoint;
};

struct tagOfflineRequestAsk : tagOfflineRequestReq {
    DWORD dwMapId;
    int nIndex;
};

struct tagOfflineRequestRes : tagOfflineRequestReq {
    BYTE nResult;
    BYTE nReason;
    DWORD dwLeftTime;
};

struct tagOfflineTimeoutRes : tagOfflineRequestReq {
    int nExtPoint;
};

struct tagPermitPlayerLogin : tagProtocolHeader2 {
    GUID guid;
    char szRoleName[32];
    bool bPermit;
};

struct tagProtocolExtendHeader : tagProtocolLengthHeader {
    BYTE m_bySubProtocolType;
};

struct tagSALE_ITEMBUSSINESS : tagSALE_BOX_SYNC {
    int nShopType;
    int nRev;
    char szShopName[32];
};
typedef tagSALE_ITEMBUSSINESS SALE_ITEMBUSSINESS;

struct tagSetHighLightPos : tagMINIMAP_OBJ_SYNC {
    DWORD dwTimeTick;
    INT nPicID;
    char szMsg[64];
};
typedef tagSetHighLightPos TSetHighLightPos;

struct tagTellFlagPos : tagMINIMAP_OBJ_SYNC {
    CHAR szMsg[64];
};
typedef tagTellFlagPos TTellFlagPos;

struct tagUseSpreaderCDKey : tagProtoHeader {
    char szAccountName[32];
    char szCDKey[32];
    int nPlayerDataIndex;
};

struct tagUseSpreaderCDKeyRet : tagProtoHeader {
    char szAccountName[32];
    int nPlayerDataIndex;
    int nResult;
};

struct CHAT_DYNCHANNEL_FINIMSG : CHAT_DYNCHANNEL_HEAD {
    WORD wChannelID;
};

struct CHAT_DYNCHANNEL_RECVMSG : CHAT_DYNCHANNEL_HEAD {
    WORD wChannelID;
    WORD wMessageLeng;
};

struct CHAT_DYNCHANNEL_SENDMSG : CHAT_DYNCHANNEL_HEAD {
    WORD wChannelID;
    char szSpeakerName[32];
    WORD wMessageLeng;
};

struct CHAT_DYNCHANNEL_SYNCMSG : CHAT_DYNCHANNEL_HEAD {
    WORD wChannelID;
    WORD wIconIndex;
    char szChannelName[260];
};

struct FIGHT_PARTNER_SIMPLE_INFO_1 : tagProtocolExtendHeader {
    DWORD m_dwID;
    BYTE m_byInfo;
};

struct FIGHT_PARTNER_SIMPLE_INFO_2 : tagProtocolExtendHeader {
    DWORD m_dwID;
    union {
        BYTE m_byInfo[2];
        WORD m_wInfo;
    };
};

struct FIGHT_PARTNER_SIMPLE_INFO_4 : tagProtocolExtendHeader {
    DWORD m_dwID;
    union {
        BYTE m_byInfo[4];
        WORD m_wInfo[2];
        DWORD m_dwInfo;
    };
};

struct FIGHT_PARTNER_SKILL_SYNC : tagProtocolExtendHeader {
    DWORD m_dwID;
    BYTE m_bySkillType;
    WORD m_wSkillID;
    WORD m_wSkillLevel;
    WORD m_wSkillExpPercent;
};

struct FIGHT_PARTNER_SYNC_ALL : tagProtocolExtendHeader {
    DWORD m_dwID;
    WORD m_wEssentialPartnerID;
    DWORD m_dwCurNpcSettingIdx;
    BYTE m_bySeries;
    WORD m_wLevel;
    DWORD m_dwCurLife;
    char m_szName[32];
    BYTE m_byCharacter;
    DWORD m_dwCurExp;
    BYTE m_byCurEmotionDegree;
    BYTE m_byCurMaxEmotionDegree;
    BYTE m_byCurVigour;
    BYTE m_byCurMaxVigour;
    BYTE m_byLifeAptitude;
    BYTE m_byStrengthAptitude;
    BYTE m_byHitTargetRateAptitude;
    BYTE m_byDefenceAptitude;
    BYTE m_bySpeedAptitude;
    BYTE m_byLuckAptitude;
    DWORD m_dwLifeAttrib;
    WORD m_wStrengthAttrib;
    WORD m_wHitTargetRateAttrib;
    WORD m_wDefenceAttrib;
    WORD m_wSpeedAttrib;
    WORD m_wLuckAttrib;
    DWORD m_arydwStandbySkillID[5];
    BYTE m_bySkillCount;
    WORD m_wTaskValueCount;
};

struct FIGHT_PARTNER_SYNC_MIN : tagProtocolExtendHeader {
    DWORD m_dwID;
    BYTE m_byAttackSpeed;
    BYTE m_byCastSpeed;
    BYTE m_byMoveSpeed;
    BYTE m_nFightFlag;
};

struct KPROTOCS_NW_INSTATE : tagProtocolExtendHeader {
    BYTE byInstate;
    char szMember[32];
    BYTE byPosition;
};

struct KPROTOCS_NW_KICKOUT : tagProtocolExtendHeader {
    DWORD dwNpcID;
};

struct KPROTOSC_NW_POSITON : tagProtocolExtendHeader {
    BYTE byPosition;
    DWORD dwMemberID;
};

struct KPROTOSC_NW_SYNCEMPEROR : tagProtocolExtendHeader {
    BYTE bySide;
    DWORD dwTongID;
    char szEmperor[32];
};

struct KPROTOSC_NW_SYNCNATIONTITLE : tagProtocolExtendHeader {
    char szTitle[32];
};

struct MIX_PROTOCOL : tagProtocolExtendHeader {
    union {
        BYTE btData[1];
        DWORD dwData[1];
        char szReserve[128];
    };
};

struct PARTNER_CTRL_INFO : tagProtocolExtendHeader {
    union {
        BYTE m_byCurPartnerIdx;
        BYTE m_byCurPartnerCallOut;
        BYTE m_byCurPartnerFollowOnly;
    };
};

struct PARTNER_NAME_SYNC : tagProtocolExtendHeader {
    DWORD m_dwID;
    char m_szName[32];
};

struct PARTNER_SIMPLE_INFO_1 : tagProtocolExtendHeader {
    BYTE m_byInfo;
};

struct PARTNER_SIMPLE_INFO_2 : tagProtocolExtendHeader {
    union {
        BYTE m_byInfo[2];
        WORD m_wInfo;
    };
};

struct PARTNER_SIMPLE_INFO_4 : tagProtocolExtendHeader {
    union {
        BYTE m_byInfo[4];
        WORD m_wInfo[2];
        DWORD m_dwInfo;
    };
};

struct PARTNER_TASK_VALUE_SYNC : tagProtocolExtendHeader {
    DWORD m_dwID;
    WORD m_wTaskID;
    DWORD m_dwTaskValue;
};

#pragma pack(pop)

#endif  // JX_PROTOCOL_H
