# Dump the inbound protocol size table out of gInitServerProtocolSize().
#
# Run inside IDA against server1/jx_linux_y, and redirect the output to
# protocol/c2s_sizes.tsv.
#
# Why this table matters: every byte a client sends passes through
#
#     KServerCore::CheckProtocolSize(nPlayerIndex, pChar, nSize, &bShutDown)
#
# which rejects the message -- and disconnects the client -- unless nSize is
# exactly what the table says for that protocol byte. So the table is the
# server's own statement of sizeof() for the inbound half of the protocol,
# recorded in code rather than in DWARF, and it is a third source to check the
# ID work against: for every fixed-size protocol, the size here must equal the
# sizeof of the packet struct that ID maps to.
#
# The indexing needs care. CheckProtocolSize reads
#
#     mov eax, ds:[esi*4 + 0x88B871C]        ; esi = the raw protocol byte
#
# while the array the initialiser fills is g_nProtocolSize @ 0x88B8820. Those
# are not the same address, and the difference is not a bug:
#
#     0x88B8820 - 0x88B871C = 0x104 = 65 * 4
#
# so the compiler folded the `- 65` of `g_nProtocolSize[byProtocol - 65]` into
# the displacement. Index 0 is protocol 65, which is also why the range gate
# just above reads `(byte - 65) <= 0xBC` -- 0xBC is 188, the last index.
#
# Two entries mean something other than a size:
#   -1  variable-length. CheckProtocolSize then takes the length from the
#       packet itself: *(WORD *)(pChar + 1) + 1, requiring nSize > 2.
#    0  never assigned. .bss starts zeroed and the initialiser skips these
#       indices, so any message with that protocol byte fails the nSize
#       comparison and the sender is disconnected. Absent, not zero-length.
#
# Read from the disassembly rather than from Hex-Rays, unlike dump_dispatch.py.
# There the array's offset inside the object and the pointer-to-member stride
# were arithmetic worth letting the decompiler do; here every store is a plain
# `mov dword ptr [eax+disp], imm` with the array's base already in eax, so the
# displacement is the index times four and there is nothing to infer.
import idc

INIT = 0x080EF560   # gInitServerProtocolSize(int *)
FIRST = 65          # protocol byte of index 0, from the displacement above


def main():
    end = idc.get_func_attr(INIT, idc.FUNCATTR_END)

    sizes = {}
    stores = 0
    dups = []

    ea = INIT
    while ea != idc.BADADDR and ea < end:
        if (idc.print_insn_mnem(ea) == "mov"
                and idc.get_operand_type(ea, 1) == idc.o_imm
                and idc.get_operand_type(ea, 0) in (idc.o_displ, idc.o_phrase)):
            idx = idc.get_operand_value(ea, 0) // 4
            # 64-bit IDA hands back a sign-extended immediate; the store is
            # dword-wide, so narrow first and then take the sign from bit 31.
            val = idc.get_operand_value(ea, 1) & 0xFFFFFFFF
            if val >= 0x80000000:
                val -= 0x100000000
            stores += 1
            # Last store wins, which is also what happens at run time.
            if idx in sizes:
                dups.append((idx, sizes[idx], val))
            sizes[idx] = val
        ea = idc.next_head(ea, end)

    fixed = sum(1 for v in sizes.values() if v > 0)
    var = sum(1 for v in sizes.values() if v == -1)

    print("# generated by tools/ida/dump_protocol_sizes.py from "
          "gInitServerProtocolSize() @ 0x%08X" % INIT)
    print("# %d stores, %d protocols assigned: %d fixed size, %d variable"
          % (stores, len(sizes), fixed, var))
    print("# index 0 is protocol %d; the %d indices not listed are left 0 by "
          ".bss and reject every length" % (FIRST, 189 - len(sizes)))
    for idx, was, now in dups:
        print("# protocol %d assigned twice: %d then %d"
              % (FIRST + idx, was, now))
    print("protocol\tsize\tkind")
    for idx in sorted(sizes):
        val = sizes[idx]
        print("%d\t%d\t%s" % (FIRST + idx, val,
                              "variable" if val == -1 else "fixed"))


if __name__ == "__main__":
    main()
