# Dump the c2s dispatch table out of KProtocolProcess::KProtocolProcess().
#
# Run inside IDA (File > Script file, or the MCP py_exec_file) against
# server1/jx_linux_y, and redirect the output to protocol/dispatch_c2s.tsv.
#
# Why this function: ProcessNetMsg does no switching at all --
#
#     byProtocol = *pMsg;
#     pfn = this->ProcessFunc[byProtocol].__pfn;
#     if (pfn) pfn(...); else printf("Unhandle Protocol %d\n", byProtocol);
#
# -- so the entire mapping from protocol byte to handler lives in the array,
# and the array is filled once, in the constructor. 2340 bytes of stores.
#
# The parse runs over the decompiler's output rather than the disassembly on
# purpose. `this->ProcessFunc[N].__pfn` is Hex-Rays having already worked out
# the array's offset inside the object and the 8-byte stride of an Itanium-ABI
# pointer-to-member; redoing that from `mov [ebx+0AAh], offset ...` would be
# our arithmetic to get wrong.
#
# Entries assigned 0 are kept. The constructor memsets the array and *then*
# explicitly nulls eleven more slots, which is not redundant -- it is the
# record of which protocols this build retired. They reach the printf.
import re

import ida_hexrays

CTOR = 0x080F0760

# `this->ProcessFunc[70].__pfn = (void (*)(...))KProtocolProcess::RemoveRole;`
# `this->ProcessFunc[65].__pfn = 0;`
ASSIGN = re.compile(
    r"this->(ProcessFunc|m_NWClientProcess|m_NWRelayProcess)\[(\d+)\]\.__pfn\s*=\s*"
    r"(?:\([^;]*?\))?\s*(?:KProtocolProcess::)?([A-Za-z_]\w*|0)\s*;")


def main():
    text = str(ida_hexrays.decompile(CTOR))

    rows = {}
    for table, idx, handler in ASSIGN.findall(text):
        # Last store wins, which is also what happens at run time.
        rows[(table, int(idx))] = handler

    live = sum(1 for v in rows.values() if v != "0")
    print("# generated by tools/ida/dump_dispatch.py from "
          "KProtocolProcess::KProtocolProcess() @ 0x%08X" % CTOR)
    print("# %d slots assigned: %d handlers, %d explicitly retired"
          % (len(rows), live, len(rows) - live))
    print("table\tid\thandler")
    for (table, idx) in sorted(rows):
        print("%s\t%d\t%s" % (table, idx, rows[(table, idx)]))


if __name__ == "__main__":
    main()
