# Recover the server-to-client protocol IDs by watching the server write them.
#
# Run inside IDA against server1/jx_linux_y; redirect stdout to
# protocol/send_ids.tsv. Takes a couple of minutes -- it decompiles everything.
#
# Why this is necessary at all: c2s_PROTOCOL survives in the binary's DWARF
# because the code declares things with that type, and s2c_PROTOCOL does not,
# because it is only ever used as a constant. Constants leave no type behind.
# Nor is the name anywhere else -- not in the relay, not in libheaven.
#
# But the server still has to *write* the ID into every packet it sends, and
# DWARF does record the type of the local it writes into. So Hex-Rays gives us
#
#     tagEnterGame eg;        // <- from DWARF
#     eg.cProtocol = 52;      // <- from the code
#
# and that pair is the mapping, observed rather than assumed. The two header
# shapes in this protocol are handled: tagProtocolHeader keeps the ID in
# cProtocol/ProtocolType at offset 0, EXTEND_HEADER splits it into
# ProtocolFamily + ProtocolID.
#
# One ID can legitimately appear from several functions, and one struct can
# carry several IDs if it is reused. Both are reported rather than collapsed --
# the disagreements are the interesting rows.
import re
from collections import defaultdict

import ida_funcs
import ida_hexrays
import idautils

FIELDS = ("cProtocol", "ProtocolType", "ProtocolFamily", "ProtocolID")

# `eg.cProtocol = 52;`  /  `v7->ProtocolType = 0x4A;`
DIRECT = re.compile(
    r"\b(\w+)\s*(?:\.|->)\s*(" + "|".join(FIELDS) + r")\s*=\s*(-?\d+|0x[0-9a-fA-F]+)\s*;")
# `((tagEnterGame *)buf)->cProtocol = 52;`
CAST = re.compile(
    r"\(\s*\(\s*(\w+)\s*\*+\s*\)[^;]*?\)\s*->\s*(" + "|".join(FIELDS) +
    r")\s*=\s*(-?\d+|0x[0-9a-fA-F]+)\s*;")

BASE = re.compile(r"[\w:]+")


def base_type(tinfo) -> str:
    """Strip pointers/arrays/qualifiers down to the struct name."""
    s = str(tinfo).replace("const ", "").replace("volatile ", "")
    s = s.split("[")[0].replace("*", " ").strip()
    m = BASE.search(s)
    return m.group(0) if m else ""


def main():
    hits = defaultdict(int)          # (struct, field, value, func) -> count
    scanned = failed = 0

    for ea in idautils.Functions():
        f = ida_funcs.get_func(ea)
        if not f:
            continue
        try:
            cfunc = ida_hexrays.decompile(ea)
        except Exception:
            failed += 1
            continue
        scanned += 1

        text = str(cfunc)
        if not any(fld in text for fld in FIELDS):
            continue

        # The local's declared type is the whole point; without it a write to
        # `.cProtocol` says nothing about which packet was being built.
        types = {}
        for lv in cfunc.get_lvars():
            if lv.name:
                types[lv.name] = base_type(lv.type())

        fname = ida_funcs.get_func_name(ea)
        for var, field, val in DIRECT.findall(text):
            struct = types.get(var)
            if struct:
                hits[(struct, field, int(val, 0), fname)] += 1
        for struct, field, val in CAST.findall(text):
            hits[(struct, field, int(val, 0), fname)] += 1

    print("# generated by tools/ida/dump_send_ids.py")
    print("# %d functions decompiled, %d failed, %d assignments found"
          % (scanned, failed, len(hits)))
    print("struct\tfield\tvalue\tfunction\tcount")
    for key in sorted(hits):
        print("%s\t%s\t%d\t%s\t%d" % (key[0], key[1], key[2], key[3], hits[key]))


if __name__ == "__main__":
    main()
